// clang-format off
// Copyright (C) Benoit Chachuat, Imperial College London.
// All Rights Reserved.
// This code is published under the EPL-2.0 with GPL-2.0-or-later as a Secondary License; see the LICENSE file.
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
// clang-format on

// GENERATED by gen_options.py from odeslv_cvodes.hpp -- do not edit; regenerate
// (cmake --build <dir> --target gen-options).

#pragma once

#include <pybind11/pybind11.h>

namespace py = pybind11;

template <class PyOpt>
void
bind_odeslv_options(PyOpt& c)
{
  c.def_readwrite("DISPLAY", &mc::ODESLV_CVODES::Options::DISPLAY,
                  "Display level (default: 1)");
  c.def_readwrite("RESRECORD", &mc::ODESLV_CVODES::Options::RESRECORD,
                  "Whether or not to record results (default: 0)");
}
