// clang-format off
// Copyright (C) Benoit Chachuat, Imperial College London.
// All Rights Reserved.
// This code is published under the EPL-2.0 with GPL-2.0-or-later as a Secondary License; see the LICENSE file.
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
// clang-format on

// GENERATED by gen_options.py from base_cvodes.hpp -- do not edit; regenerate
// (cmake --build <dir> --target gen-options).

#pragma once

#include <pybind11/pybind11.h>

namespace py = pybind11;

template <class PyOpt>
void
bind_cvodes_options(PyOpt& c)
{
  py::enum_<mc::BASE_CVODES::Options::FSA_STRATEGY>(
      c, "FSA_STRATEGY", "Enumeration type for FSA method")
      .value("SIMULTANEOUS", mc::BASE_CVODES::Options::SIMULTANEOUS,
             "Simultaneous state/sensitivity correction")
      .value("STAGGERED", mc::BASE_CVODES::Options::STAGGERED,
             "Simultaneous sensitivity corrections after state corrections")
      .value("STAGGERED1", mc::BASE_CVODES::Options::STAGGERED1,
             "Sequential sensitivity corrections after state corrections")
      .export_values();
  py::enum_<mc::BASE_CVODES::Options::ASA_STRATEGY>(
      c, "ASA_STRATEGY", "Enumeration type for ASA method")
      .value("HERMITE", mc::BASE_CVODES::Options::HERMITE,
             "Cubic Hermite interpolation")
      .value("POLYNOMIAL", mc::BASE_CVODES::Options::POLYNOMIAL,
             "Variable degree polynomial interpolation")
      .export_values();
  py::enum_<mc::BASE_CVODES::Options::INTEGRATION_METHOD>(
      c, "INTEGRATION_METHOD",
      "Enumeration of numerical integration algorithms")
      .value("MSADAMS", mc::BASE_CVODES::Options::MSADAMS,
             "Variable-coefficient linear multistep Adams method (non-stiff "
             "systems)")
      .value("MSBDF", mc::BASE_CVODES::Options::MSBDF,
             "Variable-coefficient linear multistep backward differentiation "
             "formula (BDF) method (stiff systems)")
      .export_values();
  py::enum_<mc::BASE_CVODES::Options::NONLINEAR_SOLVER>(
      c, "NONLINEAR_SOLVER", "Enumeration of nonlinear solver strategies")
      .value("FIXEDPOINT", mc::BASE_CVODES::Options::FIXEDPOINT,
             "Fixed point nonlinear solver")
      .value("NEWTON", mc::BASE_CVODES::Options::NEWTON,
             "Newton nonlinear solver")
      .export_values();
  py::enum_<mc::BASE_CVODES::Options::LINEAR_SOLVER>(
      c, "LINEAR_SOLVER",
      "Enumeration of linear solver strategies (within Newton nonlinear "
      "solver)")
      .value("DIAG", mc::BASE_CVODES::Options::DIAG,
             "Approximate diagonal Jacobian formed by way of a difference "
             "quotient")
      .value("DENSE", mc::BASE_CVODES::Options::DENSE,
             "Use analytic dense Jacobian and internal direct dense linear "
             "algebra functions")
      .value("DENSEDQ", mc::BASE_CVODES::Options::DENSEDQ,
             "Use approximate dense Jacobian by way of a difference quotient "
             "and internal direct dense linear algebra")
      .value("SPARSE", mc::BASE_CVODES::Options::SPARSE,
             "Use analytic sparse Jacobian and the KLU sparse direct solver. "
             "Requires a build with KLU")
      .export_values();
  c.def_readwrite("INTMETH", &mc::BASE_CVODES::Options::INTMETH,
                  "Numerical integration method [Default: MSBDF]");
  c.def_readwrite("NLINSOL", &mc::BASE_CVODES::Options::NLINSOL,
                  "Nonlinear solver method [Default: NEWTON]");
  c.def_readwrite(
      "LINSOL", &mc::BASE_CVODES::Options::LINSOL,
      "Linear solver method and Jacobian approximation [Default: DIAG]");
  c.def_readwrite("H0", &mc::BASE_CVODES::Options::H0,
                  "Initial step-size [Default: 0e0 (auto)]");
  c.def_readwrite("HMIN", &mc::BASE_CVODES::Options::HMIN,
                  "Minimum step-size [Default: 0e0]");
  c.def_readwrite("HMAX", &mc::BASE_CVODES::Options::HMAX,
                  "Maximum step-size [Default: 0e0 (+inf)]");
  c.def_readwrite(
      "NMAX", &mc::BASE_CVODES::Options::NMAX,
      "Maximum number of steps in a time stage [Default: 0 (2000)]");
  c.def_readwrite("RTOL", &mc::BASE_CVODES::Options::RTOL,
                  "Relative (scalar) integration tolerance");
  c.def_readwrite("ATOL", &mc::BASE_CVODES::Options::ATOL,
                  "Absolute (scalar) integration tolerance");
  c.def_readwrite(
      "ETOL", &mc::BASE_CVODES::Options::ETOL,
      "Absolute (scalar) integration tolerance for ellipsoid shape matrix");
  c.def_readwrite(
      "QERR", &mc::BASE_CVODES::Options::QERR,
      "Whether or not (state) quadrature error control is performed?");
  c.def_readwrite("MAXFAIL", &mc::BASE_CVODES::Options::MAXFAIL,
                  "Maximum number of error test failures per step");
  c.def_readwrite("MAXCORR", &mc::BASE_CVODES::Options::MAXCORR,
                  "Maximum number of nonlinear solver iterations per step");
  c.def_readwrite(
      "AUTOTOLS", &mc::BASE_CVODES::Options::AUTOTOLS,
      "Whether integration tolerances for FS are to be set automatically?");
  c.def_readwrite("RTOLS", &mc::BASE_CVODES::Options::RTOLS,
                  "Relative (scalar) integration tolerance for FSA");
  c.def_readwrite("ATOLS", &mc::BASE_CVODES::Options::ATOLS,
                  "Absolute (scalar) integration tolerance for FSA");
  c.def_readwrite("ETOLS", &mc::BASE_CVODES::Options::ETOLS,
                  "Absolute (scalar) integration tolerance for ellipsoid shape "
                  "matrix in FSA");
  c.def_readwrite("FSACORR", &mc::BASE_CVODES::Options::FSACORR,
                  "FSA correction strategy");
  c.def_readwrite("FSAERR", &mc::BASE_CVODES::Options::FSAERR,
                  "Whether or not FSA error control is performed?");
  c.def_readwrite("QERRS", &mc::BASE_CVODES::Options::QERRS,
                  "Whether or not FSA quadrature error control is performed?");
  c.def_readwrite("RTOLB", &mc::BASE_CVODES::Options::RTOLB,
                  "Relative (scalar) integration tolerance for ASA");
  c.def_readwrite("ATOLB", &mc::BASE_CVODES::Options::ATOLB,
                  "Absolute (scalar) integration tolerance for ASA");
  c.def_readwrite("ETOLB", &mc::BASE_CVODES::Options::ETOLB,
                  "Absolute (scalar) integration tolerance for ellipsoid shape "
                  "matrix in ASA");
  c.def_readwrite("QERRB", &mc::BASE_CVODES::Options::QERRB,
                  "Whether or not ASA quadrature error control is performed?");
  c.def_readwrite("ASAINTERP", &mc::BASE_CVODES::Options::ASAINTERP,
                  "ASA interpolation strategy");
  c.def_readwrite("ASACHKPT", &mc::BASE_CVODES::Options::ASACHKPT,
                  "Number of steps between each check point for ASA");
}
