// Copyright (C) Benoit Chachuat, Imperial College London.
// All Rights Reserved.
// This code is published under the Eclipse Public License.

// GENERATED by gen_options.py from odeslv_cvodes.hpp (struct at line 170) -- do
// not edit; regenerate.

#pragma once

#include <pybind11/pybind11.h>

namespace py = pybind11;

template <class PyOpt>
void
bind_odeslv_options(PyOpt& c)
{
  c.def_readwrite("DISPLAY", &mc::ODESLV_CVODES::Options::DISPLAY,
                  "Display level (default: 1)");
  c.def_readwrite("RESRECORD", &mc::ODESLV_CVODES::Options::RESRECORD,
                  "Whether or not to record results (default: 0)");
}
