// clang-format off
// Copyright (C) Benoit Chachuat, Imperial College London.
// All Rights Reserved.
// This code is published under the EPL-2.0 with GPL-2.0-or-later as a Secondary License; see the LICENSE file.
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
// clang-format on

// GENERATED by gen_options.py from ffmodel.hpp -- do not edit; regenerate
// (cmake --build <dir> --target gen-options).

#pragma once

#include <pybind11/pybind11.h>

namespace py = pybind11;

template <class PyOpt>
void
bind_ffmodel_options(PyOpt& c)
{
  py::enum_<mc::FFModel::Options::ReductionType>(c, "ReductionType",
                                                 "undocumented")
      .value("RED_NONE", mc::FFModel::Options::RED_NONE,
             "Do not perform order reduction during setup")
      .value("RED_MAIN", mc::FFModel::Options::RED_MAIN,
             "Reduce high-order derivatives, leaving earlier rows their "
             "explicit derivative")
      .value("RED_FULL", mc::FFModel::Options::RED_FULL,
             "Reduce high-order derivatives and rewrite earlier rows to use "
             "the auxiliaries")
      .export_values();
  py::enum_<mc::FFModel::Options::RobustnessMode>(c, "RobustnessMode",
                                                  "undocumented")
      .value("ROBUST_OFF", mc::FFModel::Options::ROBUST_OFF,
             "Do not sample: classify at the reference point only (default)")
      .value("ROBUST_REPORT", mc::FFModel::Options::ROBUST_REPORT,
             "Sample and report disagreement; the verdict still comes from the "
             "base point")
      .value("ROBUST_STRICT", mc::FFModel::Options::ROBUST_STRICT,
             "Sample and treat disagreement as the classification being "
             "reference-sensitive")
      .export_values();
  py::enum_<mc::FFModel::Options::ClassifyType>(
      c, "ClassifyType",
      "How setup() classifies the PDE blocks -- the values of CLASSIFY.MODE.")
      .value("CLASS_NONE", mc::FFModel::Options::CLASS_NONE,
             "Do not perform PDE classification during setup")
      .value("CLASS_AUTO", mc::FFModel::Options::CLASS_AUTO,
             "Attempt PDE classification during setup and proceed even if it "
             "fails")
      .value(
          "CLASS_STRICT", mc::FFModel::Options::CLASS_STRICT,
          "Attempt PDE classification during setup and interrupt when it fails")
      .export_values();
  c.def_readwrite(
      "DISPLAY_LEVEL", &mc::FFModel::Options::DISPLAY_LEVEL,
      "Console verbosity for setup()/eval() (default: 0). Tiered: 0 = silent: "
      "only errors, validation failures, and warnings print. 1 = key "
      "structural decisions: closures, interface-plan DROP / KEEP- EXPLICIT, "
      "continuity redundancy / value-slaved drops, order and tau reduction "
      "summaries. 2 = detailed diagnostics (includes everything at level 1): "
      "phase and [iplan] timings, trace conditioning (rcond / SVD / sparsity), "
      "per-predicate timing accumulators, verbose detection and edge "
      "breakdowns. Errors and warnings are NEVER gated by this level.");
  py::class_<mc::FFModel::Options::t_Reduce> c_REDUCE(
      c, "t_Reduce", "Order reduction of high-order derivatives.");
  c_REDUCE.def(py::init<>());
  c_REDUCE.def_readwrite(
      "ORDER", &mc::FFModel::Options::t_Reduce::ORDER,
      "Order-reduction mode applied automatically by setup. RED_NONE leaves "
      "user equations unchanged. RED_MAIN performs first-order reduction "
      "without substituting matching first-order derivative nodes in "
      "pre-existing equations. RED_FULL also reuses the new auxiliary states "
      "in matching pre-existing equations; this is the default.");
  c_REDUCE.def_readwrite(
      "NONLINEAR_PARTIALS", &mc::FFModel::Options::t_Reduce::NONLINEAR_PARTIALS,
      "Materialise first-order state-partials that appear NON-AFFINELY in a "
      "residual. reduce_order already peels high-order partials, and already "
      "materialises the partials carried INSIDE an OpI/OpEval operand "
      "(materialize_operand_partials), because a nonlocal reduction LINK "
      "cannot expose an inner OpP. It does NOT touch a first-order "
      "OpP(state,dir) sitting in an ordinary residual, which is right when the "
      "residual is AFFINE in it -- the principal-symbol proxy and the "
      "collocation Jacobian both handle a variable-coefficient derivative. It "
      "is NOT right when the derivative is wrapped nonlinearly: a DIVISION by "
      "a derivative (the ALE/moving-mesh 1/x_xi, u_xi/x_xi, u_xi/x_xi^2) or a "
      "transcendental of one (an arclength monitor sqrt(1+u_xi^2)). Those "
      "force a driver to hand-roll the derivative as a state with its own "
      "defining equation -- and hand-rolled auxiliaries are invisible to the "
      "classifier AS auxiliaries, which is how the multiply-defined flux "
      "states and the rectangular symbols in the moving-mesh drivers arose. "
      "When true, such a partial is minted as a derivative auxiliary Dp with a "
      "defining LINK OpP(state,dir) - Dp = 0 and substituted everywhere -- "
      "exactly the mint/LINK/reuse protocol the OpI/OpEval operand path "
      "already uses. The residual then contains only the STATE Dp inside the "
      "nonlinearity, and the raw OpP survives solely in a LINK, which is an "
      "ordinary differential equation the proxy pass resolves. The trigger is "
      "per-partial and minimal: a partial is materialised iff the residual is "
      "not AFFINE in THAT partial alone (mc::FFDep type != L). So `D*u_z`, "
      "`u*u_z`, `exp(-u)*u_z` are untouched, and in `(c-x_t)*u_xi/x_xi` ONLY "
      "x_xi is materialised -- x_t and u_xi remain ordinary "
      "variable-coefficient partials. Every residual that is affine in each of "
      "its first-order partials -- the entire existing corpus -- is therefore "
      "bit-identical. Default false: opt in, sweep, then consider promoting. "
      "Requires REDUCE.ORDER != RED_NONE.");
  c_REDUCE.def_readwrite(
      "HIDDEN_IC", &mc::FFModel::Options::t_Reduce::HIDDEN_IC,
      "Materialise the HIDDEN constraints of a high-index reduction as INITIAL "
      "rows at the evolution boundary, so the model declares only the FREE "
      "initial data (default true since 2026-10-04; false was the former "
      "convention of one declared initial condition per differential state, "
      "made consistent by hand). A reduction that differentiates a constraint "
      "k times implies k lower levels which hold at the initial point but are "
      "not rows: with this off, the model must declare one initial condition "
      "per evolution-differential state and make the redundant ones consistent "
      "by hand (initial_data() says how many they are); with it on, those "
      "levels ARE rows, the free data alone makes the system square, and a "
      "full declaration is reported as a surplus by the DOF audit. Which data "
      "is free is a modelling choice -- for the index-3 pendulum {x,u} works, "
      "{x,y} does not.");
  c.def_readwrite("REDUCE", &mc::FFModel::Options::REDUCE,
                  "Order reduction of high-order derivatives.");
  py::class_<mc::FFModel::Options::t_Classify> c_CLASSIFY(
      c, "t_Classify", "Classification of each block's principal symbol.");
  c_CLASSIFY.def(py::init<>());
  c_CLASSIFY.def_readwrite("MODE", &mc::FFModel::Options::t_Classify::MODE,
                           "PDE classification during setup(): CLASS_AUTO "
                           "(default), CLASS_NONE or CLASS_STRICT");
  c_CLASSIFY.def_readwrite(
      "ROBUST", &mc::FFModel::Options::t_Classify::ROBUST,
      "Reference-robustness sampling (see RobustnessMode). (0 = off, 1 = "
      "report, 2 = strict).");
  c_CLASSIFY.def_readwrite(
      "NSAMPLE", &mc::FFModel::Options::t_Classify::NSAMPLE,
      "Number of angular samples for no-evolution-domain classification.");
  c_CLASSIFY.def_readwrite(
      "IMAG_TOL", &mc::FFModel::Options::t_Classify::IMAG_TOL,
      "Imaginary-part/rank tolerance used by automatic classification.");
  c.def_readwrite("CLASSIFY", &mc::FFModel::Options::CLASSIFY,
                  "Classification of each block's principal symbol.");
  py::class_<mc::FFModel::Options::t_Auto> c_AUTO(
      c, "t_Auto",
      "Automatic model transformations applied at setup(): boundary closures "
      "and differential elimination.");
  c_AUTO.def(py::init<>());
  c_AUTO.def_readwrite(
      "HYP_CLOSURE", &mc::FFModel::Options::t_Auto::HYP_CLOSURE,
      "auto closure of the OUTFLOW faces of hyperbolic blocks: appends the "
      "missing outgoing-characteristic rows (default on). Off: the model must "
      "close every outflow face itself (e.g. its PDE extended to the face) -- "
      "setup REFUSES (HYP_CLOSURE_MISSING) when rows are missing, as an "
      "under-determined system would be solved silently wrong");
  c_AUTO.def_readwrite(
      "DIFF_ELIM", &mc::FFModel::Options::t_Auto::DIFF_ELIM,
      "auto differential-elimination of algebraically-determined derivatives "
      "(substitute + relocate consumer onto source face); OFF by default");
  c.def_readwrite("AUTO", &mc::FFModel::Options::AUTO,
                  "Automatic model transformations applied at setup(): "
                  "boundary closures and differential elimination.");
  c.def_readwrite(
      "TTOL", &mc::FFModel::Options::TTOL,
      "Two time points closer than this are the SAME point (1e-9). A consumer "
      "that stages a model -- an integrator, a marching solve, anything that "
      "stops at boundaries -- must decide whether a function's time point "
      "coincides with an element boundary, and an exact comparison is the "
      "wrong test for a value that was typed or computed. Absolute, in the "
      "units of the evolution domain.");
  c.def_readwrite(
      "MAXTHREAD", &mc::FFModel::Options::MAXTHREAD,
      "cap on the threads the numerical backends may use inside setup() and "
      "solve(). SPQR, SuperLU, UMFPACK, KLU and every dense LAPACK call take "
      "their parallelism from the SAME BLAS/OpenMP layer, so ONE cap covers "
      "them all -- SPQR has no thread pool of its own (its TBB path was "
      "removed upstream, and cc.SPQR_nthreads is now inert). 0 (default) "
      "imposes NO cap: the runtime is left exactly as the environment set it. "
      "n>0 caps to n for the duration of the call and RESTORES the previous "
      "setting on every exit. NOTE the deliberate difference from "
      "FFGraph::Options:: MAXTHREAD, which reads 0 as "
      "\"hardware_concurrency\": here 0 means \"do not touch\", so an outer "
      "OMP_NUM_THREADS or a cluster allocation is respected rather than "
      "overridden. MEASURED (PDE5, 9 audit windows): cap=1 is 18% FASTER than "
      "the uncapped run -- 152.4 s against 186.0 s of rank time. Environment: "
      "CRONOS_MAXTHREAD.");
}
