// Copyright (C) Benoit Chachuat, Imperial College London.
// All Rights Reserved.
// This code is published under the Eclipse Public License.

// GENERATED by gen_options.py from ocfeslv.hpp -- do not edit; regenerate
// (cmake --build <dir> --target gen-options).

#pragma once

#include <pybind11/pybind11.h>

namespace py = pybind11;

template <class PyOpt>
void
bind_ocfeslv_options(PyOpt& c)
{
  py::enum_<mc::OCPlan::InterfaceType>(
      c, "InterfaceType",
      "the interface-condition type. ONE definition, OCPlan's: ocplan.hpp sits "
      "below this header in the include order, and it had carried an identical "
      "copy whose comment said it \"must stay in sync\" with FFModel's. "
      "Aliased here, with its enumerators re-exported, so Options::IC_VALUE "
      "and OCFESLV::Options::IC_AUTO resolve exactly as before.")
      .value("IC_VALUE", mc::OCPlan::IC_VALUE, "OCPlan::IC_VALUE")
      .value("IC_FLUX", mc::OCPlan::IC_FLUX, "OCPlan::IC_FLUX")
      .value("IC_UPWIND", mc::OCPlan::IC_UPWIND, "OCPlan::IC_UPWIND")
      .value("IC_AUTO", mc::OCPlan::IC_AUTO, "OCPlan::IC_AUTO")
      .export_values();
  py::enum_<mc::OCPlan::ImpositionSentinel>(
      c, "ImpositionType",
      "the imposition type. ONE definition, OCPlan's (ocplan.hpp sits below "
      "this header), aliased here with its values re-exported -- as "
      "InterfaceType is -- so no static_assert has to keep two copies in step.")
      .value("IC_WEAK", mc::OCPlan::IMPOSITION_IC_WEAK,
             "OCPlan::IMPOSITION_IC_WEAK")
      .value("IC_STRONG", mc::OCPlan::IMPOSITION_IC_STRONG,
             "OCPlan::IMPOSITION_IC_STRONG")
      .value("IC_TRACE", mc::OCPlan::IMPOSITION_IC_TRACE,
             "OCPlan::IMPOSITION_IC_TRACE")
      .export_values();
  py::enum_<mc::OCFESLV::Options::InterfaceDropPolicy>(c, "InterfaceDropPolicy",
                                                       "undocumented")
      .value("DROP_VERIFY", mc::OCFESLV::Options::DROP_VERIFY,
             "structural drop + post-solve verify gate (default)")
      .value("DROP_REDERIVE", mc::OCFESLV::Options::DROP_REDERIVE,
             "verify-driven re-derive: protect over-dropped claims, re-solve")
      .value("DROP_OFF", mc::OCFESLV::Options::DROP_OFF,
             "disable the drop; keep all continuity claims explicit")
      .export_values();
  py::enum_<mc::OCFESLV::Options::DerivCacheType>(c, "DerivCacheType",
                                                  "undocumented")
      .value("DERIV_LAZY", mc::OCFESLV::Options::DERIV_LAZY, "DERIV_LAZY")
      .value("DERIV_EAGER", mc::OCFESLV::Options::DERIV_EAGER, "DERIV_EAGER")
      .export_values();
  py::enum_<mc::OCFESLV::Options::LinearEvalCacheType>(c, "LinearEvalCacheType",
                                                       "undocumented")
      .value("LINEAR_NONE", mc::OCFESLV::Options::LINEAR_NONE, "LINEAR_NONE")
      .value("LINEAR_LAZY", mc::OCFESLV::Options::LINEAR_LAZY, "LINEAR_LAZY")
      .value("LINEAR_EAGER", mc::OCFESLV::Options::LINEAR_EAGER, "LINEAR_EAGER")
      .export_values();
  py::enum_<mc::OCFESLV::Options::OutputGridPolicy>(c, "OutputGridPolicy",
                                                    "undocumented")
      .value("OUT_ELEMENT_LOCAL", mc::OCFESLV::Options::OUT_ELEMENT_LOCAL,
             "OUT_ELEMENT_LOCAL")
      .value("OUT_UNIQUE_PHYSICAL", mc::OCFESLV::Options::OUT_UNIQUE_PHYSICAL,
             "OUT_UNIQUE_PHYSICAL")
      .export_values();
  py::enum_<mc::OCFESLV::Options::SolveFactorization>(
      c, "SolveFactorization",
      "Sparse linear factorization backend for the internal LM/Newton solve. "
      "SOLVE_SUPERLU uses arma::spsolve with SuperLU (requires the Armadillo "
      "build to define ARMA_USE_SUPERLU); when it is not linked the solver "
      "transparently falls back to a densifying LAPACK solve (one-time "
      "notice). SOLVE_LAPACK forces the densifying dense-LU path (small/debug "
      "systems). The enum is left extensible for a future UMFPACK/other direct "
      "backend without touching call sites.")
      .value("SOLVE_SUPERLU", mc::OCFESLV::Options::SOLVE_SUPERLU,
             "sparse SuperLU (arma::spsolve), default. The solver only ever")
      .value("SOLVE_LAPACK", mc::OCFESLV::Options::SOLVE_LAPACK,
             "densify the damped operator and use dense LU (debug / small "
             "systems)")
      .value("SOLVE_SPQR", mc::OCFESLV::Options::SOLVE_SPQR,
             "sparse rank-revealing QR (SuiteSparseQR) min-2-norm least "
             "squares on")
      .export_values();
  py::enum_<mc::OCFESLV::Options::SolveWarmstart>(
      c, "SolveWarmstart",
      "Warm-start strategy for the per-element step of a SOLVE.MARCHING solve.")
      .value("REUSE", mc::OCFESLV::Options::REUSE,
             "reuse the previous element's converged state as the next guess "
             "(free; default)")
      .value("BROADCAST_IC", mc::OCFESLV::Options::BROADCAST_IC,
             "seed every evolution node of the next element with the "
             "transferred IC profile")
      .value("EXTRAPOLATE", mc::OCFESLV::Options::EXTRAPOLATE,
             "linear/quadratic extrapolation from the last one/two elements' "
             "terminals")
      .export_values();
  py::enum_<mc::OCFESLV::Options::NT_SKIP_MODE>(c, "NT_SKIP_MODE",
                                                "undocumented")
      .export_values();
  py::enum_<mc::OCFESLV::Options::DETERMINACY_BACKEND_T>(
      c, "DETERMINACY_BACKEND_T",
      "Rank backend of the determinacy audit (2026-10-09: one value per line, "
      "so that the Python binder registers them -- the one-line form left the "
      "enum empty in Python).")
      .value("DET_AUTO", mc::OCFESLV::Options::DET_AUTO,
             "SuiteSparseQR if built, else Eigen if built, else dense under "
             "the cap (default)")
      .value("DET_SPQR", mc::OCFESLV::Options::DET_SPQR,
             "SuiteSparseQR only; refused by setup() in a build without it "
             "(BACKEND_UNAVAILABLE)")
      .value("DET_EIGEN", mc::OCFESLV::Options::DET_EIGEN,
             "Eigen's sparse QR only; refused by setup() in a build without "
             "Eigen (BACKEND_UNAVAILABLE)")
      .value("DET_DENSE", mc::OCFESLV::Options::DET_DENSE,
             "dense SVD only, under the size cap")
      .export_values();
  py::class_<mc::OCFESLV::Options::t_Interface> c_INTERFACE(
      c, "t_Interface",
      "How continuity between elements is expressed and imposed: the condition "
      "type, the imposition (penalty, trace multiplier, strong), SAT penalties "
      "and trace-multiplier scaling.");
  c_INTERFACE.def(py::init<>());
  c_INTERFACE.def_readwrite(
      "IMPOSITION", &mc::OCFESLV::Options::t_Interface::IMPOSITION,
      "Imposition strategy for interface conditions: IC_STRONG (default since "
      "2026-10-06; exact continuity rows), IC_WEAK (penalty terms of strength "
      "SAT_SIGMA0) or IC_TRACE (trace multipliers)");
  c_INTERFACE.def_readwrite(
      "TYPE", &mc::OCFESLV::Options::t_Interface::TYPE,
      "Interface condition type for multi-element continuity");
  c_INTERFACE.def_readwrite(
      "SAT_SIGMA0", &mc::OCFESLV::Options::t_Interface::SAT_SIGMA0,
      "SAT penalty coefficient for C0 (value) continuity. Effective penalty = "
      "INTERFACE.SAT_SIGMA0 * \\tau_d per direction d. Default 10.0 (since "
      "2026-10-03; 1.0 was below threshold at moderate refinement -- a ~10x "
      "worse answer, silently -- and 100 can stall the monolithic Newton "
      "solve). Default penalty parameter for direction d: \\tau_d = (n_node - "
      "1)^2 / w_elem (spectral scaling) scaled by INTERFACE.SAT_SIGMA0 (C0 "
      "continuity) or CRONOS_SAT_SIGMA1 (C1). When classify_pde() has been "
      "called, the penalty is coupled through the principal symbol: \\sum_j "
      "A_d[k,j] * \\sigma * \\tau_d * \\Delta u_j.");
  c_INTERFACE.def_readwrite(
      "DROP_POLICY", &mc::OCFESLV::Options::t_Interface::DROP_POLICY,
      "Policy for the IC_TRACE/IC_STRONG redundant-continuity drop (item 10). "
      "DROP_VERIFY keeps the structural receiver-B drop and treats a "
      "post-solve over-drop (verify_interface_drop) as a hard failure. "
      "DROP_REDERIVE additionally lets the driver protect the over-dropped "
      "claims and re-derive/re-solve until the verify gate is clean (correct "
      "on the linear suite, and the safe path for the nonlinear case). "
      "DROP_OFF disables the drop entirely (every continuity claim kept "
      "explicit) -- the most conservative, always-correct baseline.");
  c_INTERFACE.def_readwrite(
      "TRACE_TAU_SCALE", &mc::OCFESLV::Options::t_Interface::TRACE_TAU_SCALE,
      "Column scaling for generated IC_TRACE tau variables. Claim-centred "
      "multipliers enter receiver rows as INTERFACE.TRACE_TAU_SCALE*lambda. "
      "The projected u-solution is unchanged, but a non-unit value can improve "
      "conditioning when tau variables are much larger/smaller than state "
      "rows.");
  c_INTERFACE.def_readwrite("TRACE_PROJ_MAX",
                            &mc::OCFESLV::Options::t_Interface::TRACE_PROJ_MAX,
                            "Largest n_trace_var for which the trace projector "
                            "is computed; 0 disables the guard. Default 6000.");
  c_INTERFACE.def_readwrite(
      "TRACE_PROJ_EPS", &mc::OCFESLV::Options::t_Interface::TRACE_PROJ_EPS,
      "Multiplier-block regularisation for the trace projection. The k "
      "continuity conditions the receiver graph cannot support are enforced "
      "through a spring of stiffness 1/eps rather than dropped. Default 1.0.");
  c.def_readwrite(
      "INTERFACE", &mc::OCFESLV::Options::INTERFACE,
      "How continuity between elements is expressed and imposed: the condition "
      "type, the imposition (penalty, trace multiplier, strong), SAT penalties "
      "and trace-multiplier scaling.");
  py::class_<mc::OCFESLV::Options::t_Solve> c_SOLVE(
      c, "t_Solve",
      "The nonlinear solve: Newton/Levenberg-Marquardt control, linear "
      "backend, marching, reuse, evaluation caches, and the solver's own "
      "verbosity.");
  c_SOLVE.def(py::init<>());
  c_SOLVE.def_readwrite("FACTORIZATION",
                        &mc::OCFESLV::Options::t_Solve::FACTORIZATION,
                        "linear backend (default SOLVE_SUPERLU; see note)");
  c_SOLVE.def_readwrite("MARCHING", &mc::OCFESLV::Options::t_Solve::MARCHING,
                        "auto-march when AVAILABLE (evolution domain + >=1 "
                        "differential state); else monolithic (default true)");
  c_SOLVE.def_readwrite("RES_TOL", &mc::OCFESLV::Options::t_Solve::RES_TOL,
                        "accept on max|r| (1e-9)");
  c_SOLVE.def_readwrite(
      "MAX_ITER", &mc::OCFESLV::Options::t_Solve::MAX_ITER,
      "@name Internal nonlinear-solve (LM/Newton) controls — see "
      "OCFESLV::solve(). Defaults reproduce the legacy driver harness "
      "numerics. @{ max LM/Newton iterations (30)");
  c_SOLVE.def_readwrite("WARMSTART", &mc::OCFESLV::Options::t_Solve::WARMSTART,
                        "per-element warm-start strategy for a SOLVE.MARCHING "
                        "solve (default REUSE)");
  c_SOLVE.def_readwrite("VERBOSE", &mc::OCFESLV::Options::t_Solve::VERBOSE,
                        "per-iteration LM/Newton trace to stdout (true)");
  c_SOLVE.def_readwrite("REUSE", &mc::OCFESLV::Options::t_Solve::REUSE,
                        "reuse last converged monolithic solution at the same "
                        "input (default true)");
  c_SOLVE.def_readwrite("LAMBDA0", &mc::OCFESLV::Options::t_Solve::LAMBDA0,
                        "initial LM damping (1e-8)");
  c_SOLVE.def_readwrite("LAMBDA_DROP",
                        &mc::OCFESLV::Options::t_Solve::LAMBDA_DROP,
                        "lambda *= this on an accepted LM step (0.25)");
  c_SOLVE.def_readwrite("LAMBDA_RAISE",
                        &mc::OCFESLV::Options::t_Solve::LAMBDA_RAISE,
                        "lambda *= this on a failed factorization/step (10.0)");
  c_SOLVE.def_readwrite("LAMBDA_MIN",
                        &mc::OCFESLV::Options::t_Solve::LAMBDA_MIN,
                        "lambda floor (1e-14)");
  c_SOLVE.def_readwrite("LS_MAX", &mc::OCFESLV::Options::t_Solve::LS_MAX,
                        "backtracking line-search steps (24)");
  c_SOLVE.def_readwrite("ARMIJO_C", &mc::OCFESLV::Options::t_Solve::ARMIJO_C,
                        "Armijo sufficient-decrease constant (1e-4)");
  c_SOLVE.def_readwrite("EQUILIBRATE",
                        &mc::OCFESLV::Options::t_Solve::EQUILIBRATE,
                        "row/col inf-norm equilibration (true)");
  c_SOLVE.def_readwrite(
      "DERIV_CACHE", &mc::OCFESLV::Options::t_Solve::DERIV_CACHE,
      "Derivative sparsity/coloring cache policy. DERIV_LAZY postpones FFDep "
      "sparsity propagation and coloring until a derivative/sparsity query "
      "needs them; DERIV_EAGER preserves the older setup-time behaviour.");
  c_SOLVE.def_readwrite(
      "LINEAR_EVAL_CACHE", &mc::OCFESLV::Options::t_Solve::LINEAR_EVAL_CACHE,
      "Linear residual cache policy. When enabled, purely linear rows are "
      "evaluated by a cached sparse affine map r = A z + b whenever the "
      "supplied constants match the setup constants. Nonlinear rows and "
      "changing constants fall back to normal OCVar evaluation.");
  c_SOLVE.def_readwrite(
      "DISPLAY_LEVEL", &mc::OCFESLV::Options::t_Solve::DISPLAY_LEVEL,
      "Solver-side verbosity, independent of the inherited DISPLAY_LEVEL: the "
      "model reports its plan, claims and classification, the solver its "
      "iterations, factorisation and marching. The default, -1, follows the "
      "model's DISPLAY_LEVEL, resolved each time it is read (so a driver may "
      "set DISPLAY_LEVEL after construction); set it in code to make the two "
      "differ. Not an environment knob. MAXTHREAD is deliberately not "
      "duplicated -- it is a process-global RAII cap.");
  c.def_readwrite("SOLVE", &mc::OCFESLV::Options::SOLVE,
                  "The nonlinear solve: Newton/Levenberg-Marquardt control, "
                  "linear backend, marching, reuse, evaluation caches, and the "
                  "solver's own verbosity.");
  py::class_<mc::OCFESLV::Options::t_Output> c_OUTPUT(
      c, "t_Output", "What the solver retains and emits after a solve.");
  c_OUTPUT.def(py::init<>());
  c_OUTPUT.def_readwrite("MARCH_STORE",
                         &mc::OCFESLV::Options::t_Output::MARCH_STORE,
                         "SOLVE.MARCHING: keep each element's block solution "
                         "(O(N)) for plotting/inspection via "
                         "march_trajectory()/eval_solution() (default true)");
  c_OUTPUT.def_readwrite(
      "GRID_POLICY", &mc::OCFESLV::Options::t_Output::GRID_POLICY,
      "Grid policy for distributed post-evaluation outputs only. "
      "OUT_ELEMENT_LOCAL keeps one output row per element-local collocation "
      "coefficient, including duplicate physical interface points for LGL/CGL. "
      "OUT_UNIQUE_PHYSICAL skips the duplicate left trace of every non-first "
      "LGL/CGL element in distributed output dimensions. Equations, states, "
      "node_colloc(), interface/SAT handling and scalar point outputs remain "
      "element-local.");
  c.def_readwrite("OUTPUT", &mc::OCFESLV::Options::OUTPUT,
                  "What the solver retains and emits after a solve.");
  py::class_<mc::OCFESLV::Options::t_Audit> c_AUDIT(
      c, "t_Audit",
      "Reports that diagnose the user's MODEL. They change what is printed, "
      "never the result.");
  c_AUDIT.def(py::init<>());
  c_AUDIT.def_readwrite(
      "EQN_LEGEND", &mc::OCFESLV::Options::t_Audit::EQN_LEGEND,
      "print the eN -> equation legend (roles, bare states, partial orders per "
      "direction) at the end of setup() (false). Printed unconditionally at "
      "the head of a spectrum audit regardless of this flag. The legend is "
      "what makes an audit's \"by eqn eN\" resolvable against the model, and "
      "its `partials` column identifies the assembled formulation "
      "independently of any banner. Environment default: CRONOS_AUDIT_LEGEND, "
      "else CRONOS_AUDIT.");
  c_AUDIT.def_readwrite(
      "COVERAGE", &mc::OCFESLV::Options::t_Audit::COVERAGE,
      "print the structural column-coverage report and the claim census at the "
      "end of setup() (false). Setup-time only: no solve, no SVD. A state "
      "column covered by NO row is a free degree of freedom; singly-covered "
      "columns are the fragility margin. Necessary, not sufficient -- see the "
      "method doc. Environment default: CRONOS_AUDIT_COVERAGE, else "
      "CRONOS_AUDIT.");
  c_AUDIT.def_readwrite(
      "SPECTRUM", &mc::OCFESLV::Options::t_Audit::SPECTRUM,
      "run the singular-value / left+right null-space audit at iteration 0 of "
      "every solve(), not only when tier-0 Newton is found singular (false). "
      "Needed to compare a CONVERGING run against a failing one: the "
      "historical trigger fired only on failure, so a wrong-but-converged "
      "solve was never audited. Environment default: CRONOS_AUDIT_SPECTRUM "
      "(NOT implied by CRONOS_AUDIT).");
  c_AUDIT.def_readwrite(
      "SPECTRUM_MAX", &mc::OCFESLV::Options::t_Audit::SPECTRUM_MAX,
      "largest dense-SVD the spectrum audit will attempt, in either dimension. "
      "Was a hard literal 3000, which put `rel` out of reach on exactly the "
      "configurations where the question lives (MMPDE13 at production order "
      "reaches the limit by NEL_T=4). Cost is O(n^3): 3000 is seconds, 6000 a "
      "few minutes. Environment: CRONOS_SPECTRUM_MAX.");
  c_AUDIT.def_readwrite(
      "RANK_SYMMETRY", &mc::OCFESLV::Options::t_Audit::RANK_SYMMETRY,
      "print the saddle-point rank-symmetry report at the end of setup(): rank "
      "of the multiplier column block B against rank of the continuity row "
      "block C. rank(B) < n_trace_var makes the augmented system singular for "
      "ANY C and cannot be repaired by dropping or pinning rows. Environment "
      "default: CRONOS_AUDIT_RANK, else CRONOS_AUDIT.");
  c.def_readwrite("AUDIT", &mc::OCFESLV::Options::AUDIT,
                  "Reports that diagnose the user's MODEL. They change what is "
                  "printed, never the result.");
  py::class_<mc::OCFESLV::Options::t_Determinacy> c_DETERMINACY(
      c, "t_Determinacy",
      "The numerical-rank determinacy audit run at the end of setup().");
  c_DETERMINACY.def(py::init<>());
  c_DETERMINACY.def_readwrite(
      "AUDIT", &mc::OCFESLV::Options::t_Determinacy::AUDIT,
      "run the numerical-rank determinacy audit at the end of setup() (false). "
      "One report line per audited window, unconditional on DISPLAY_LEVEL. "
      "Environment: CRONOS_AUDIT_DETERMINACY.");
  c_DETERMINACY.def_readwrite(
      "TOL", &mc::OCFESLV::Options::t_Determinacy::TOL,
      "the SINGLE relative rank tolerance, applied identically to rank(M) and "
      "rank([B;D]) (1e-12; the value the spectrum audit's rank_deficiency[] "
      "uses).");
  c_DETERMINACY.def_readwrite(
      "BACKEND", &mc::OCFESLV::Options::t_Determinacy::BACKEND,
      "rank backend: DET_AUTO = SPQR if built, else Eigen if built, else dense "
      "under the cap. Values: AUTO|SPQR|EIGEN|DENSE. An explicit DET_SPQR / "
      "DET_EIGEN in a build without that backend is REFUSED by setup() "
      "(BACKEND_UNAVAILABLE) -- it used to skip the check silently.");
  c.def_readwrite(
      "DETERMINACY", &mc::OCFESLV::Options::DETERMINACY,
      "The numerical-rank determinacy audit run at the end of setup().");
  py::class_<mc::OCFESLV::Options::t_Sensitivity> c_SENSITIVITY(
      c, "t_Sensitivity",
      "The linear solve inside the forward/adjoint sensitivity computation.");
  c_SENSITIVITY.def(py::init<>());
  c_SENSITIVITY.def_readwrite(
      "SPARSE", &mc::OCFESLV::Options::t_Sensitivity::SPARSE,
      "assemble the sensitivity Jacobian SPARSELY and solve with arma::spsolve "
      "(SuperLU) instead of a dense arma::mat + arma::lu. WHY. The dense "
      "Jacobian is ~2.6 GB at 18202^2 and O(n^3) to factorise -- a scalability "
      "wall INDEPENDENT of the singularity question, and one that affects "
      "IC_WEAK fixed-mesh models too. It has simply not bitten yet because "
      "every fsens/asens driver in the corpus is small. The primal path has "
      "been sparse throughout. WHAT IT DOES NOT DO. Sparse LU is still LU. It "
      "does NOT make the interface-augmented systems that fail today succeed "
      "-- it reports the same singularity, though it fails cleanly (SuperLU "
      "throws) instead of falling into a dense approximate solve that does not "
      "terminate usefully. That is better DIAGNOSABILITY, not better "
      "capability. Reliability is tier 1 (SPQR). This is TIER 0 of the "
      "eventual design, mirroring the primal: SuperLU normally, rank-revealing "
      "QR when nTrace > 0. Default ON; set false for the dense path.");
  c.def_readwrite(
      "SENSITIVITY", &mc::OCFESLV::Options::SENSITIVITY,
      "The linear solve inside the forward/adjoint sensitivity computation.");
  py::class_<mc::OCFESLV::Options::t_Homotopy> c_HOMOTOPY(
      c, "t_Homotopy",
      "Continuation in the parameters registered with add_homotopy().");
  c_HOMOTOPY.def(py::init<>());
  c_HOMOTOPY.def_readwrite(
      "ENABLE", &mc::OCFESLV::Options::t_Homotopy::ENABLE,
      "honour homotopy parameters registered with add_homotopy() (true). When "
      "false the schedule is IGNORED and solve() runs directly at the current "
      "input values -- useful for with/without contrast runs without "
      "unregistering the model's parameters.");
  c_HOMOTOPY.def_readwrite(
      "STEP_CAP", &mc::OCFESLV::Options::t_Homotopy::STEP_CAP,
      "max homotopy step in s, and the step the ramp STARTS at (0.1). PATH "
      "FIDELITY KNOB, and the one that matters: a converged step is NOT "
      "evidence of correctness -- too large a cap can move the corrector onto "
      "a different solution branch with no warning.");
  c_HOMOTOPY.def_readwrite(
      "STEP_GROW", &mc::OCFESLV::Options::t_Homotopy::STEP_GROW,
      "step growth after an accepted step (1.4). Only acts as the RECOVERY "
      "rate after a backtrack, since the ramp starts at the cap.");
  c_HOMOTOPY.def_readwrite(
      "STEP_SHRINK", &mc::OCFESLV::Options::t_Homotopy::STEP_SHRINK,
      "step shrink after a failed step (0.5). *** REQUIRED: HOMOTOPY.STEP_GROW "
      "* HOMOTOPY.STEP_SHRINK < 1. *** Otherwise a step near the critical size "
      "alternates fail/succeed forever (shrink then grow returns it above the "
      "failing value), wasting one solve per accepted step. The asymmetry -- "
      "shrink fast, grow slowly -- is what makes the step ratchet down and "
      "settle.");
  c_HOMOTOPY.def_readwrite("STEP_MIN",
                           &mc::OCFESLV::Options::t_Homotopy::STEP_MIN,
                           "abandon stage below this step (1e-5)");
  c_HOMOTOPY.def_readwrite(
      "AUTO_DESTAGE", &mc::OCFESLV::Options::t_Homotopy::AUTO_DESTAGE,
      "when a multi-parameter stage fails, split it into sequential "
      "single-parameter sub-stages from the point it reached, rather than "
      "giving up (true). Announced LOUDLY on stderr and recorded in "
      "StageReport::destaged: needing it usually says something about the "
      "MODEL -- those parameters interact too strongly to move together -- so "
      "it should be noticed, not silently absorbed.");
  c_HOMOTOPY.def_readwrite("PREDICT",
                           &mc::OCFESLV::Options::t_Homotopy::PREDICT,
                           "guarded extrapolation predictor (true)");
  c_HOMOTOPY.def_readwrite(
      "PREDICT_ORDER", &mc::OCFESLV::Options::t_Homotopy::PREDICT_ORDER,
      "max order of the extrapolation from accepted points (2). 0 = plain "
      "reuse, 1 = secant (2 points), 2 = quadratic (3 points). Every candidate "
      "up to this order is TRIED and the smallest-residual one is kept, so "
      "raising it can only help: a worse extrapolation is discarded for the "
      "price of one residual evaluation. NOTE a TANGENT predictor is "
      "deliberately ABSENT. It is redundant with the corrector's first Newton "
      "step: at a converged x(s) with the parameters moved to s+ds, "
      "r(x,p(s+ds)) ~ ds*dr/ds, so the first Newton step is -J^-1 r ~ ds*dx/ds "
      "-- the tangent itself. Computing it explicitly would cost a Jacobian "
      "and a factorization to save the very iteration that produces it. "
      "Extrapolation from already-accepted points needs neither.");
  c.def_readwrite(
      "HOMOTOPY", &mc::OCFESLV::Options::HOMOTOPY,
      "Continuation in the parameters registered with add_homotopy().");
  py::class_<mc::OCFESLV::Options::t_Fatal> c_FATAL(
      c, "t_Fatal", "Which conditions make setup() FAIL rather than warn.");
  c_FATAL.def(py::init<>());
  c_FATAL.def_readwrite(
      "DETERMINACY", &mc::OCFESLV::Options::t_Fatal::DETERMINACY,
      "setup() returns false (SetupStatus::DETERMINACY_UNDETERMINED) on a "
      "STATE CONTENT verdict (false).");
  c_FATAL.def_readwrite(
      "INTERFACE_RANK", &mc::OCFESLV::Options::t_Fatal::INTERFACE_RANK,
      "setup() returns false (INTERFACE_PLAN_INVALID) when the multiplier "
      "block B is column rank-deficient. Default FALSE: the resulting kernel "
      "is singular but not always fatal (a model whose residual satisfies the "
      "compatibility conditions still converges), so this stays opt-in until "
      "the corpus has been re-baselined.");
  c_FATAL.def_readwrite(
      "EVOLUTION_DOMAIN", &mc::OCFESLV::Options::t_Fatal::EVOLUTION_DOMAIN,
      "setup() returns false on an unsuitable evolution domain or an IC that "
      "cannot be set consistently (true); false (default) downgrades to a "
      "DISPLAY_LEVEL warning and proceeds");
  c_FATAL.def_readwrite(
      "REDUCED_DOF", &mc::OCFESLV::Options::t_Fatal::REDUCED_DOF,
      "setup() returns false on a structurally IC/BC-inconsistent reduced "
      "system (true); false downgrades to a warning and proceeds "
      "(rank-revealing solve)");
  c.def_readwrite("FATAL", &mc::OCFESLV::Options::FATAL,
                  "Which conditions make setup() FAIL rather than warn.");
}
