// Copyright (C) Benoit Chachuat, Imperial College London.
// All Rights Reserved.
// This code is published under the EPL-2.0 with GPL-2.0-or-later as a Secondary License; see the LICENSE file.
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later

// Python binding of OCFESLV: the orthogonal-collocation-on-finite-elements
// solver of an FFModel (monolithic or marching), with forward and adjoint
// sensitivity analysis of its outputs.
#include "ocfeslv.hpp"

#include <pybind11/functional.h>
#include <pybind11/iostream.h>
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <functional>
#include <limits>
#include <optional>

// generated by gen_options.py; it needs the classes above
#include "gen_ocfeslv_options.hpp"

namespace py = pybind11;

namespace
{
typedef mc::OCFESLV O;
typedef mc::FFModel M;
typedef py::array_t<double> t_Arr;
typedef py::call_guard<py::scoped_ostream_redirect, py::scoped_estream_redirect>
    t_Redirect;

// The C++ solver works in place on raw arrays: require a writable, contiguous
// float64 NumPy array of exactly the expected size (no silent copy, no overrun)
double*
buffer(py::handle h, size_t n, char const* what)
{
  if (!py::isinstance<py::array>(h))
    throw py::type_error(std::string("OCFESLV: '") + what +
                         "' must be a NumPy array (float64)");
  py::array a = py::reinterpret_borrow<py::array>(h);
  if (!a.dtype().is(py::dtype::of<double>()))
    throw py::type_error(std::string("OCFESLV: '") + what +
                         "' must have dtype float64");
  if (!(a.flags() & py::array::c_style) || !a.writeable())
    throw py::value_error(std::string("OCFESLV: '") + what +
                          "' must be C-contiguous and writable");
  if ((size_t)a.size() != n)
    throw py::value_error(std::string("OCFESLV: '") + what + "' has " +
                          std::to_string(a.size()) + " entries, " +
                          std::to_string(n) + " expected");
  return static_cast<double*>(a.mutable_data());
}

// constants: None (no constant) or one value per constant
std::vector<double>
constants(O const& self, std::optional<std::vector<double>> const& cst)
{
  size_t const nc       = self.var_constant().size();
  std::vector<double> c = cst ? *cst : std::vector<double>();
  if (c.size() != nc)
    throw py::value_error("OCFESLV: " + std::to_string(nc) +
                          " constant value(s) expected, " +
                          std::to_string(c.size()) + " given");
  return c;
}

double*
inp_ptr(O const& self, py::object const& inp)
{
  return inp.is_none() ? nullptr : buffer(inp, self.n_colloc_inp(), "inp");
}

char const* DOC_SOLVE_ARGS = R"doc(
Parameters
----------
var : numpy.ndarray
    Collocation state coefficients (float64, size ``n_colloc_sta()``): the
    initial guess, overwritten IN PLACE with the solution.
inp : numpy.ndarray, optional
    Collocation input coefficients (float64, size ``n_colloc_inp()``), e.g.
    from ``init`` and ``set_input_values``.
cst : list of float, optional
    Constant values, in the order of ``var_constant``.
)doc";
}  // namespace

void
mc_ocfeslv(py::module_& m)
{
  // OCFESLV derives from FFModel and OCBase (C++ multiple inheritance):
  // py::multiple_inheritance() makes pybind11 adjust the pointer when an
  // FFModel method is called on an OCFESLV.
  py::class_<O, M> pyOCFESLV(m, "OCFESLV", py::multiple_inheritance(), R"doc(
Solver of an FFModel by orthogonal collocation on finite elements (OCFE), in
one monolithic solve or marching along the evolution direction
(``options.SOLVE.MARCHING``), with forward (``solve_fsens``) and adjoint
(``solve_asens``) sensitivity analysis of the outputs with respect to the
registered controls.

The model is declared through the FFModel methods; ``setup()`` analyses it and
builds the collocation system. The unknowns live in NumPy arrays: ``init()``
returns the collocation state vector ``var`` (initial guess from the
references) and the input vector ``inp``; ``set_input_values`` fills inputs;
``solve`` overwrites ``var`` with the solution.

Example -- the heat equation u_t = u_zz with an output:

>>> S = OCFESLV(G)
>>> ... declare domains, states, equations, outputs ...
>>> S.setup()
>>> var, inp = S.init()
>>> rep = S.solve(var, inp)
>>> rep.converged, S.val_functions()
)doc");

  // --- OCFESLV SolveReport ---
  py::class_<O::SolveReport>(pyOCFESLV, "SolveReport", "Outcome of a solve.")
      .def_readonly("converged", &O::SolveReport::converged,
                    "max|r| <= options.SOLVE.RES_TOL at return")
      .def_readonly(
          "reused", &O::SolveReport::reused,
          "returned from the SOLVE.REUSE primal cache (no Newton run)")
      .def_readonly("iterations", &O::SolveReport::iterations,
                    "accepted outer iterations")
      .def_readonly("newton_steps", &O::SolveReport::newton_steps,
                    "accepted undamped-Newton steps")
      .def_readonly("lm_steps", &O::SolveReport::lm_steps,
                    "accepted damped-LM steps")
      .def_readonly("initial_residual", &O::SolveReport::initial_residual,
                    "max|r| at the supplied guess")
      .def_readonly("final_residual", &O::SolveReport::final_residual,
                    "max|r| at return")
      .def_readonly("final_merit", &O::SolveReport::final_merit,
                    "0.5 * ||row-scaled r||^2 at return")
      .def(
          "__bool__", [](O::SolveReport const& r) { return r.converged; },
          "True if converged.")
      .def("__repr__",
           [](O::SolveReport const& r)
           {
             std::ostringstream os;
             os << "SolveReport(converged=" << (r.converged ? "True" : "False")
                << ", iterations=" << r.iterations
                << ", final_residual=" << r.final_residual << ")";
             return os.str();
           });

  // --- OCFESLV Options ---
  py::class_<O::Options, M::Options> pyOpt(pyOCFESLV, "Options", R"doc(
Options of OCFESLV: the model options (FFModel.Options) and the collocation
solver options, grouped as INTERFACE, SOLVE, OUTPUT, AUDIT, DETERMINACY,
SENSITIVITY, HOMOTOPY and FATAL.
)doc");
  pyOpt.def(py::init<>()).def(py::init<O::Options const&>());
  bind_ocfeslv_options(pyOpt);

  // --- OCFESLV EqnOptions ---
  py::class_<O::EqnOptions, M::EqnOptions>(pyOCFESLV, "EqnOptions", R"doc(
Options of one equation for OCFESLV: the model options (role, block) and the
local interface-condition settings.
)doc")
      .def(py::init<M::EqnRole, int, O::Options::InterfaceType>(),
           py::arg_v("role", M::EqnRole::AUTO, "FFModel.EqnRole.AUTO"),
           py::arg("block_id") = 0,
           py::arg_v("interface_type", O::Options::IC_AUTO,
                     "OCFESLV.Options.IC_AUTO"),
           "Options with role-derived defaults.")
      .def(py::init<M::EqnRole, int, O::Options::InterfaceType, bool, bool,
                    bool>(),
           py::arg("role"), py::arg("block_id"), py::arg("interface_type"),
           py::arg("classify"), py::arg("sat"), py::arg("donate") = false,
           R"doc(
Options with explicit flags (the role invariants still apply: an INTERFACE row
never enters classification).
)doc")
      .def_readwrite("interface_type", &O::EqnOptions::interface_type,
                     "local interface-condition type (IC_AUTO: resolved)")
      .def_readwrite("receive_sat", &O::EqnOptions::receive_sat,
                     "may receive weak (SAT) interface penalties")
      .def_readwrite("donate_for_state_continuity",
                     &O::EqnOptions::donate_for_state_continuity,
                     "may be donated as a duplicate trace row");

  // --- OCFESLV Main Class ---
  pyOCFESLV
      .def_static("revision", []() { return std::string(O::revision()); },
                  "The revision of the solver (ocfeslv.hpp).  FFModel.revision() gives the model\n"
                  "layer's, which a build may combine with another solver revision.")
      .def(py::init<mc::FFGraph*>(), py::arg("dag"), py::keep_alive<1, 2>(),
           "Empty solver and model on the DAG ``dag`` (kept alive by it).")
      .def_property(
          "options", [](O& self) -> O::Options& { return self.options; },
          [](O& self, O::Options const& o) { self.options = o; },
          py::return_value_policy::reference_internal,
          "Solver options (model and collocation); transferred at ``setup()``.")
      .def(
          "init",
          [](O& self, std::optional<std::vector<double>> const& cst)
          {
            std::vector<double> var, inp;
            std::vector<double> const c = constants(self, cst);
            if (!self.init(var, inp, c))
              throw std::runtime_error(
                  "OCFESLV.init failed (see the messages above)");
            return py::make_tuple(t_Arr(var.size(), var.data()),
                                  t_Arr(inp.size(), inp.data()));
          },
          py::arg("cst") = py::none(), t_Redirect(), R"doc(
The collocation vectors after ``setup()``: ``(var, inp)`` as NumPy arrays --
``var`` the state coefficients initialised from the references, ``inp`` the
input coefficients initialised from the input references.

Parameters
----------
cst : list of float, optional
    Constant values, in the order of ``var_constant``.
)doc")
      .def(
          "solve",
          [](O& self, py::object var, py::object inp,
             std::optional<std::vector<double>> const& cst)
          {
            double* pv = buffer(var, self.n_colloc_sta(), "var");
            double* pi = inp_ptr(self, inp);
            std::vector<double> const c = constants(self, cst);
            return self.solve(pv, pi, c.empty() ? nullptr : c.data());
          },
          py::arg("var"), py::arg("inp") = py::none(),
          py::arg("cst") = py::none(), t_Redirect(),
          (std::string(
               "Solve the collocation system; returns a SolveReport.\n") +
           DOC_SOLVE_ARGS)
              .c_str())
      .def(
          "solve_fsens",
          [](O& self, py::object var, py::object inp,
             std::optional<std::vector<double>> const& cst)
          {
            double* pv = buffer(var, self.n_colloc_sta(), "var");
            double* pi = inp_ptr(self, inp);
            std::vector<double> const c = constants(self, cst);
            return self.solve_fsens(pv, pi, c.empty() ? nullptr : c.data());
          },
          py::arg("var"), py::arg("inp") = py::none(),
          py::arg("cst") = py::none(), t_Redirect(),
          (std::string(
               "Solve, then the forward sensitivities of the outputs with "
               "respect to the registered controls (``sens_jacobian``); "
               "returns True on success.\n") +
           DOC_SOLVE_ARGS)
              .c_str())
      .def(
          "solve_asens",
          [](O& self, py::object var, py::object inp,
             std::optional<std::vector<double>> const& cst)
          {
            double* pv = buffer(var, self.n_colloc_sta(), "var");
            double* pi = inp_ptr(self, inp);
            std::vector<double> const c = constants(self, cst);
            return self.solve_asens(pv, pi, c.empty() ? nullptr : c.data());
          },
          py::arg("var"), py::arg("inp") = py::none(),
          py::arg("cst") = py::none(), t_Redirect(),
          (std::string(
               "Solve, then the adjoint sensitivities of the outputs with "
               "respect to the registered controls (``sens_jacobian``); "
               "returns True on success.\n") +
           DOC_SOLVE_ARGS)
              .c_str())
      // values
      .def(
          "val_functions", [](O const& self) { return self.val_functions(); },
          "Output values after the last solve.")
      .def(
          "eval_solution",
          [](O const& self, mc::FFVar const& state, M::t_Coord const& pt)
          { return self.eval_solution(state, pt); }, py::arg("state"),
          py::arg("point"), R"doc(
Value of ``state`` at ``point`` (a dict ``{domain: coordinate}``) in the last
converged solution, in EITHER solve mode: the cached primal of a monolithic
solve (``options.SOLVE.REUSE``) or the stored windows of a marching solve
(``options.OUTPUT.MARCH_STORE``) -- both on by default.
)doc")
      .def(
          "march_grid", [](O const& self) { return self.march_grid(); },
          "The window boundaries of the march (empty for a monolithic setup).")
      .def(
          "march_trajectory",
          [](O const& self)
          {
            py::list L;
            for (auto const& b : self.march_trajectory())
              L.append(
                  py::dict(py::arg("t0") = b.t0, py::arg("t1") = b.t1,
                           py::arg("var") = t_Arr(b.var.size(), b.var.data()),
                           py::arg("inp") = t_Arr(b.inp.size(), b.inp.data())));
            return L;
          },
          R"doc(
The stored windows of the last marching solve
(``options.OUTPUT.MARCH_STORE``): one dict per window with ``t0``, ``t1`` and
the window's collocated ``var`` and ``inp`` (NumPy arrays).
)doc")
      .def(
          "blk_fct",
          [](O const& self, size_t ndx)
          {
            auto const b = self.blk_fct(ndx);
            if (b.first == std::numeric_limits<size_t>::max())
              throw py::index_error("OCFESLV.blk_fct: no output " +
                                    std::to_string(ndx) +
                                    " (outputs are numbered in add_output() "
                                    "order, after setup())");
            return py::make_tuple(b.first, b.second);
          },
          py::arg("ndx"), R"doc(
The block of output ``ndx`` (in add_output() order) in ``val_functions()``:
``(first, count)`` -- one value for a point output, one per selected node for
a distributed output.
)doc")
      .def(
          "sens_functions", [](O const& self) { return self.sens_functions(); },
          "Output values captured by the last solve_fsens / solve_asens.")
      .def(
          "sens_jacobian",
          [](O const& self)
          {
            std::vector<double> const& J = self.sens_jacobian();
            size_t const nf = self.n_colloc_fct(), nd = self.n_control_dof();
            if (J.empty()) return t_Arr(std::vector<size_t>{0, nd});
            if (J.size() != nf * nd)
              throw std::runtime_error("OCFESLV: sens_jacobian size mismatch");
            return t_Arr(std::vector<size_t>{nf, nd}, J.data());
          },
          R"doc(
Jacobian of the outputs with respect to the control DOFs, captured by the last
solve_fsens / solve_asens: NumPy array of shape (nf, n_control_dof), columns
in the order of the registered controls and their ``control_dofs``.
)doc")
      // inputs
      .def(
          "set_input_values",
          [](O const& self, mc::FFVar const& u, std::vector<double> const& vals,
             py::object inp)
          {
            if (!self.set_input_values(u, vals,
                                       buffer(inp, self.n_colloc_inp(), "inp")))
              throw py::value_error(
                  "OCFESLV.set_input_values: " + u.name() +
                  " is not a declared input, or the size is wrong");
          },
          py::arg("input"), py::arg("values"), py::arg("inp"), R"doc(
Write the collocated values of input ``input`` into ``inp`` (in place):
element-major, node-inner, as ``get_input_values`` reads them.
)doc")
      .def(
          "sample_input",
          [](O const& self, mc::FFVar const& u, M::t_Fun const& fun,
             py::object inp)
          {
            if (!self.sample_input(u, fun,
                                   buffer(inp, self.n_colloc_inp(), "inp")))
              throw py::value_error("OCFESLV.sample_input: " + u.name() +
                                    " is not a declared input");
          },
          py::arg("input"), py::arg("fun"), py::arg("inp"), R"doc(
Write input ``input`` into ``inp`` (in place) from a function ``fun({domain:
coordinate}) -> float`` evaluated at its collocation nodes.
)doc")
      .def(
          "get_input_values",
          [](O const& self, mc::FFVar const& u, py::object inp)
          {
            return self.get_input_values(
                u, buffer(inp, self.n_colloc_inp(), "inp"));
          },
          py::arg("input"), py::arg("inp"),
          "The collocated values of input ``input`` in ``inp``.")
      .def(
          "encode_controls",
          [](O const& self, py::object inp)
          {
            std::vector<double> p;
            self.encode_controls(buffer(inp, self.n_colloc_inp(), "inp"), p);
            return p;
          },
          py::arg("inp"),
          "The control DOF values held in ``inp``, in the order of the "
          "gradient columns.")
      .def(
          "decode_controls",
          [](O const& self, std::vector<double> const& p, py::object inp)
          {
            if (p.size() != self.n_control_dof())
              throw py::value_error("OCFESLV.decode_controls: " +
                                    std::to_string(self.n_control_dof()) +
                                    " values expected");
            self.decode_controls(p, buffer(inp, self.n_colloc_inp(), "inp"));
          },
          py::arg("p"), py::arg("inp"),
          "Write the control DOF values ``p`` into ``inp`` (in place).")
      // sizes and structure
      .def(
          "n_colloc_sta", [](O const& self) { return self.n_colloc_sta(); },
          "Size of ``var``: collocation state coefficients.")
      .def(
          "n_colloc_inp", [](O const& self) { return self.n_colloc_inp(); },
          "Size of ``inp``: collocation input coefficients.")
      .def(
          "n_colloc_eqn", [](O const& self) { return self.n_colloc_eqn(); },
          "Number of collocation equation residuals.")
      .def(
          "n_colloc_fct", [](O const& self) { return self.n_colloc_fct(); },
          "Number of scalar output functions.")
      .def(
          "n_colloc_trace", [](O const& self) { return self.n_colloc_trace(); },
          "Number of trace variables (0 under IC_STRONG).")
      .def_property_readonly(
          "states_colloc", [](O const& self) { return self.states_colloc(); },
          "The states of the collocation system (after order reduction).")
      .def(
          "node_colloc", [](O const& self, mc::FFVar const& var)
          { return self.node_colloc(var); }, py::arg("var"),
          "The collocation node coordinates of state or input ``var``.")
      .def(
          "is_marching", [](O const& self) { return self.is_marching(); },
          "True if the model is solved by marching.")
      .def(
          "n_march_steps", [](O const& self) { return self.n_march_steps(); },
          "Number of march steps.");
}
