// Copyright (C) Benoit Chachuat, Imperial College London.
// All Rights Reserved.
// This code is published under the Eclipse Public License.

// Python binding of ODESLV (C++ ODESLVS_CVODES): the CVODES solver of an
// FFModel, with forward (solve_fsens) and adjoint (solve_asens) sensitivity
// analysis. Replaces the binding of the retired description interface
// (set_time, set_state, set_differential, ...): the model is declared through
// FFModel.
#include <pybind11/functional.h>
#include <pybind11/iostream.h>
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <functional>
#include <sstream>
#include <variant>

#include "odeslvs_cvodes.hpp"

// generated by gen_options.py; they need the classes above
#include "gen_cvodes_options.hpp"
#include "gen_odeslv_options.hpp"

namespace py = pybind11;

namespace
{
typedef mc::ODESLVS_CVODES S;
typedef mc::FFModel M;
typedef std::function<double(M::DofIndex const&)> t_Gen;
typedef std::variant<std::vector<double>, t_Gen> t_Val;
typedef std::map<mc::FFVar, t_Val, mc::lt_FFVar> t_Inputs;
typedef py::call_guard<py::scoped_ostream_redirect, py::scoped_estream_redirect>
    t_Redirect;

// {input: values or generator} -> the C++ by-name list (FFModel::InputVal)
std::vector<M::InputVal>
input_vals(t_Inputs const& in)
{
  std::vector<M::InputVal> v;
  for (auto const& [u, val] : in)
  {
    if (std::holds_alternative<t_Gen>(val))
      v.emplace_back(u, std::get<t_Gen>(val));
    else
      v.emplace_back(u, std::get<std::vector<double>>(val));
  }
  return v;
}

// Recorded trajectories as NumPy arrays (copies): built from the C++ records,
// whose x holds a first block of nx values (states, or adjoint states) followed
// by a second block (quadratures, or the running gradient)
typedef py::array_t<double> t_Arr;
struct t_ResSolve
{
  t_Arr t, x, q;
};
struct t_ResFsens
{
  t_Arr t, xp, qp;
};
struct t_ResAsens
{
  t_Arr t, l, qp;
};

// one list of records -> t (n,), first block (n, n1), second block (n, n2)
void
records(std::vector<S::Results> const& R, size_t n1, t_Arr& t, t_Arr& a,
        t_Arr& b, bool reverse)
{
  size_t const n = R.size(), n2 = n ? R[0].x.size() - n1 : 0;
  t      = t_Arr(std::vector<py::ssize_t>{py::ssize_t(n)});
  a      = t_Arr(std::vector<py::ssize_t>{py::ssize_t(n), py::ssize_t(n1)});
  b      = t_Arr(std::vector<py::ssize_t>{py::ssize_t(n), py::ssize_t(n2)});
  auto T = t.mutable_unchecked<1>();
  auto A = a.mutable_unchecked<2>();
  auto B = b.mutable_unchecked<2>();
  for (size_t k = 0; k < n; ++k)
  {
    auto const& r = R[reverse ? n - 1 - k : k];
    if (r.x.size() != n1 + n2)
      throw std::runtime_error("ODESLV: inconsistent record sizes");
    T(k) = r.t;
    for (size_t i = 0; i < n1; ++i) A(k, i) = r.x[i];
    for (size_t i = 0; i < n2; ++i) B(k, i) = r.x[n1 + i];
  }
}

// several lists of records (one per direction or output) -> t (n,), first (m,
// n, n1), second (m, n, n2)
void
records(std::vector<std::vector<S::Results>> const& RR, size_t n1, t_Arr& t,
        t_Arr& a, t_Arr& b, bool reverse)
{
  size_t const m = RR.size(), n = m ? RR[0].size() : 0;
  size_t const n2 = n ? RR[0][0].x.size() - n1 : 0;
  a      = t_Arr(std::vector<py::ssize_t>{py::ssize_t(m), py::ssize_t(n),
                                          py::ssize_t(n1)});
  b      = t_Arr(std::vector<py::ssize_t>{py::ssize_t(m), py::ssize_t(n),
                                          py::ssize_t(n2)});
  auto A = a.mutable_unchecked<3>();
  auto B = b.mutable_unchecked<3>();
  for (size_t j = 0; j < m; ++j)
  {
    if (RR[j].size() != n)
      throw std::runtime_error("ODESLV: inconsistent record counts");
    t_Arr tj, aj, bj;
    records(RR[j], n1, tj, aj, bj, reverse);
    if (j == 0) t = tj;
    auto Aj = aj.unchecked<2>();
    auto Bj = bj.unchecked<2>();
    for (size_t k = 0; k < n; ++k)
    {
      for (size_t i = 0; i < n1; ++i) A(j, k, i) = Aj(k, i);
      for (size_t i = 0; i < n2; ++i) B(j, k, i) = Bj(k, i);
    }
  }
  if (!m) t = t_Arr(std::vector<py::ssize_t>{py::ssize_t(size_t(0))});
}

char const* DOC_BYNAME = R"doc(
The values are given BY NAME: a dict mapping every declared input and constant
to its values -- a list (one value for a parameter or a constant; one per DOF
for a distributed input, in the order of ``control_dofs``) or a generator
``gen(dof: FFModel.DofIndex) -> float``. An incomplete or inconsistent dict
raises ``ValueError``, naming the entry.
)doc";
}  // namespace

void
mc_odeslv(py::module_& m)
{
  // FFModel is a VIRTUAL base of ODESLVS_CVODES (at a non-zero offset):
  // py::multiple_inheritance() makes pybind11 adjust the pointer when an
  // FFModel method is called on an ODESLV. pybind11 >= 3.1 detects virtual
  // bases itself; older versions reinterpret the pointer, so FFModel methods
  // would run on the wrong address.
  py::class_<S, M> pyODESLV(m, "ODESLV", py::multiple_inheritance(), R"doc(
Solver of an FFModel by CVODES (SUNDIALS): integration of the model along its
evolution direction, with forward (``solve_fsens``) and adjoint
(``solve_asens``) sensitivity analysis of its outputs.

The model is declared through the FFModel methods (domains, states, inputs,
equations, outputs, transitions); ``setup()`` analyses it and builds the
integrator. Inputs are either passed positionally (the parameter vector of
``var_parameter``) or by name (a dict).

Example -- x' = -p x, x(0) = 1, output x(1):

>>> from pymcpp import FFGraph, FFPartial, FFEval
>>> from cronos import FFDom, ODESLV
>>> G = FFGraph(); t, x, p = G.add_var("t"), G.add_var("x"), G.add_var("p")
>>> OpP, OpE = FFPartial(), FFEval()
>>> S = ODESLV(G)
>>> S.add_domain(t, FFDom(0., 1., 2)); S.set_evolution_domain(t)
>>> S.add_state(x, [t]); S.add_input(p)
>>> S.add_equation(OpP(x, t) + p*x, [t], [FFDom.ALL - FFDom.LB])
>>> S.add_equation(x - 1., [t], [FFDom.LB])
>>> S.add_output(OpE(x, t, 1.))
>>> S.setup()
>>> S.solve({p: [0.7]}); S.val_function()        # [exp(-0.7)]
)doc");

  // --- ODESLV enums ---
  py::enum_<S::STATUS>(pyODESLV, "STATUS", "Status of an integration.")
      .value("NORMAL", S::NORMAL, "Normal execution")
      .value("FAILURE", S::FAILURE, "Integration breakdown")
      .value("FATAL", S::FATAL,
             "Interruption due to errors in third-party libraries")
      .export_values();

  // --- ODESLV Options ---
  py::class_<mc::ODESLV_CVODES::Options, M::Options> pyOpt(pyODESLV, "Options",
                                                           R"doc(
Options of ODESLV: the model options (FFModel.Options) and the CVODES options
(integration method, nonlinear and linear solvers, tolerances, sensitivity
settings).
)doc");
  pyOpt.def(py::init<>()).def(py::init<mc::ODESLV_CVODES::Options const&>());
  bind_cvodes_options(pyOpt);
  bind_odeslv_options(pyOpt);

  // --- ODESLV records ---
  py::class_<t_ResSolve>(pyODESLV, "ResultsSolve", R"doc(
Trajectories recorded by the last ``solve`` (``options.RESRECORD`` points), as
NumPy arrays.
)doc")
      .def_readonly("t", &t_ResSolve::t,
                    "Time points, shape (n,); a stage boundary appears twice "
                    "(values on either side).")
      .def_readonly("x", &t_ResSolve::x,
                    "States, shape (n, nx), in the order of ``var_state``.")
      .def_readonly("q", &t_ResSolve::q, "Quadratures, shape (n, nq).");

  py::class_<t_ResFsens>(pyODESLV, "ResultsFsens", R"doc(
Trajectories recorded by the last ``solve_fsens``, as NumPy arrays: one block
per sensitivity direction (``sensitivity_index``).
)doc")
      .def_readonly("t", &t_ResFsens::t,
                    "Time points, shape (n,); a stage boundary appears twice "
                    "(values on either side).")
      .def_readonly("xp", &t_ResFsens::xp,
                    "State sensitivities, shape (nsen, n, nx).")
      .def_readonly("qp", &t_ResFsens::qp,
                    "Quadrature sensitivities, shape (nsen, n, nq).");

  py::class_<t_ResAsens>(pyODESLV, "ResultsAsens", R"doc(
Trajectories recorded by the last ``solve_asens``, as NumPy arrays: one block
per output function, in ASCENDING time (the adjoint integration runs
backward).
)doc")
      .def_readonly(
          "t", &t_ResAsens::t,
          "Time points, ascending, shape (n,); a stage boundary appears twice.")
      .def_readonly("l", &t_ResAsens::l, "Adjoint states, shape (nf, n, nx).")
      .def_readonly("qp", &t_ResAsens::qp, R"doc(
Running gradient of each output with respect to the sensitivity directions,
shape (nf, n, nsen); its value at t = 0 is the gradient.
)doc");

  py::class_<mc::BASE_CVODES::Stats>(pyODESLV, "Stats", R"doc(
Statistics of an integration.
)doc")
      .def_readonly("cputime", &mc::BASE_CVODES::Stats::cputime,
                    "CPU time (seconds).")
      .def_readonly("numSteps", &mc::BASE_CVODES::Stats::numSteps,
                    "Number of steps.")
      .def_readonly("numRHS", &mc::BASE_CVODES::Stats::numRHS,
                    "Number of right-hand-side evaluations.")
      .def_readonly("numJAC", &mc::BASE_CVODES::Stats::numJAC,
                    "Number of Jacobian evaluations.");

  // --- ODESLV Main Class ---
  pyODESLV.def_static("revision", []() { return std::string(S::revision()); },
                      "The revision of the ODESLV headers (odeslv_base.hpp and the three that change with it), e.g.\n"
                      "for a bug report; FFModel.revision() gives the model layer's.");
  pyODESLV
      .def(py::init<mc::FFGraph*>(), py::arg("dag"), py::keep_alive<1, 2>(),
           "Empty solver and model on the DAG ``dag`` (kept alive by it).")
      .def_property(
          "options",
          [](S& self) -> mc::ODESLV_CVODES::Options& { return self.options; },
          [](S& self, mc::ODESLV_CVODES::Options const& o)
          { self.options = o; }, py::return_value_policy::reference_internal,
          "Solver options (model and CVODES).")
      .def(
          "setup", [](S& self) { return self.setup(); }, t_Redirect(),
          R"doc(
Analyse the model and build the integrator; returns False on failure (see
``extract_error`` and ``setup_status``). Output written by C++ is redirected
to Python's ``sys.stdout`` / ``sys.stderr``.
)doc")
      .def(
          "extract_error", [](S const& self) { return self.extract_error(); },
          "Why the model could not be extracted as an ODE system (empty if it "
          "could).")
      // solves: positional
      .def(
          "solve",
          [](S& self, std::vector<double> const& p,
             std::vector<double> const& c)
          { return self.solve(p, c, std::cout); },
          py::arg("p"), py::arg("c") = std::vector<double>(), t_Redirect(),
          R"doc(
Integrate the model.

Parameters
----------
p : list of float
    Parameter values, in the order of ``var_parameter``.
c : list of float, optional
    Constant values, in the order of ``var_constant``.

Returns
-------
ODESLV.STATUS
)doc")
      .def(
          "solve", [](S& self, t_Inputs const& in)
          { return self.solve(input_vals(in), std::cout); }, py::arg("inputs"),
          t_Redirect(),
          (std::string("Integrate the model.\n") + DOC_BYNAME).c_str())
      .def(
          "solve_fsens",
          [](S& self, std::vector<double> const& p,
             std::vector<double> const& c)
          { return self.solve_fsens(p, c, std::cout); },
          py::arg("p"), py::arg("c") = std::vector<double>(), t_Redirect(),
          R"doc(
Integrate the model and its forward sensitivities with respect to the
sensitivity directions (``sensitivity_index``: the control DOFs, or every
parameter when no control is registered). Arguments as ``solve``.
)doc")
      .def(
          "solve_fsens", [](S& self, t_Inputs const& in)
          { return self.solve_fsens(input_vals(in), std::cout); },
          py::arg("inputs"), t_Redirect(),
          (std::string("Integrate the model and its forward sensitivities.\n") +
           DOC_BYNAME)
              .c_str())
      .def(
          "solve_asens",
          [](S& self, std::vector<double> const& p,
             std::vector<double> const& c)
          { return self.solve_asens(p, c, std::cout); },
          py::arg("p"), py::arg("c") = std::vector<double>(), t_Redirect(),
          R"doc(
Integrate the model forward and its adjoints backward, for the gradients of
the outputs with respect to the sensitivity directions. Arguments as
``solve``.
)doc")
      .def(
          "solve_asens", [](S& self, t_Inputs const& in)
          { return self.solve_asens(input_vals(in), std::cout); },
          py::arg("inputs"), t_Redirect(),
          (std::string("Integrate the model and its adjoints.\n") + DOC_BYNAME)
              .c_str())
      // values
      .def(
          "val_function", [](S const& self) { return self.val_function(); },
          "Output values after the last solve.")
      .def(
          "blk_fct",
          [](S const& self, size_t ndx)
          {
            auto const b = self.blk_fct(ndx);
            if (b.first == std::numeric_limits<size_t>::max())
              throw py::index_error("ODESLV.blk_fct: no output " +
                                    std::to_string(ndx) +
                                    " (outputs are numbered in add_output() "
                                    "order, after setup())");
            return py::make_tuple(b.first, b.second);
          },
          py::arg("ndx"), R"doc(
The block of output ``ndx`` (in add_output() order) in ``val_function()``:
``(first, count)``.  An ODESLV integrates a lumped system and returns one value
per output, so the block is ``(ndx, 1)``.  The same call exists on ``OCFESLV``,
where a distributed output spans several values.
)doc")
      .def(
          "val_function_gradient",
          [](S const& self) { return self.val_function_gradient(); },
          R"doc(
Output gradients after the last sensitivity solve: one row per sensitivity
direction (``sensitivity_index``), one column per output.
)doc")
      .def(
          "val_function_gradient", [](S const& self, mc::FFVar const& var)
          { return self.val_function_gradient(var); }, py::arg("var"), R"doc(
Output gradients with respect to the DOFs of the control ``var`` only: one row
per DOF (in the order of ``control_dofs``), one column per output.
)doc")
      .def(
          "val_function_gradient",
          [](S const& self, mc::FFVar const& var,
             std::map<mc::FFVar, size_t, mc::lt_FFVar> const& ndx_el)
          { return self.val_function_gradient(var, ndx_el); },
          py::arg("var"), py::arg("ndx_el"), R"doc(
Output gradients with respect to the DOFs of the control ``var`` in one
element, ``{evolution domain: element}`` (ignored for a time-invariant
control).
)doc")
      .def(
          "val_state", [](S const& self) { return self.val_state(); },
          "State values at the stage times after the last solve.")
      // sizes
      .def(
          "np", [](S const& self) { return self.np(); },
          "Number of parameters.")
      .def(
          "nf", [](S const& self) { return self.nf(); },
          "Number of output functions.")
      .def(
          "nx", [](S const& self) { return self.nx(); }, "Number of states.")
      .def(
          "nq", [](S const& self) { return self.nq(); },
          "Number of quadratures.")
      .def(
          "ns", [](S const& self) { return self.ns(); }, "Number of stages.")
      // parameters
      .def_property_readonly(
          "var_parameter", [](S const& self) { return self.var_parameter(); },
          R"doc(
The parameter vector the solver integrates against: the time-invariant inputs
and, for each time-varying input, its per-element nodal values.
)doc")
      .def(
          "pos_input",
          [](S const& self, mc::FFVar const& var,
             std::map<mc::FFVar, size_t, mc::lt_FFVar> const& ndx_el)
          { return self.pos_input(var, ndx_el); },
          py::arg("var"),
          py::arg("ndx_el") = std::map<mc::FFVar, size_t, mc::lt_FFVar>(),
          "Position of input ``var`` (in element ``ndx_el``) in the parameter "
          "vector.")
      .def(
          "parameter_index", [](S const& self, mc::FFVar const& w)
          { return self.parameter_index(w); }, py::arg("var"),
          "Positions of input ``var``'s values in the parameter vector.")
      .def_property_readonly(
          "sensitivity_index",
          [](S const& self) { return self.sensitivity_index(); },
          "Parameter positions of the sensitivity directions, in order.")
      .def(
          "set_parameter_values",
          [](S const& self, mc::FFVar const& w, std::vector<double> const& vals,
             std::vector<double> P)
          {
            if (!self.set_parameter_values(w, vals, P))
              throw std::invalid_argument(
                  "set_parameter_values: " + w.name() +
                  " is not a parameter-input, or a size is wrong");
            return P;
          },
          py::arg("var"), py::arg("values"), py::arg("p"), R"doc(
Return a copy of the parameter vector ``p`` with the values of input ``var``
replaced by ``values``.
)doc")
      .def(
          "get_parameter_values",
          [](S const& self, mc::FFVar const& w, std::vector<double> const& P)
          { return self.get_parameter_values(w, P); }, py::arg("var"),
          py::arg("p"),
          "The values of input ``var`` in the parameter vector ``p``.")
      // recorded trajectories and statistics
      .def_property_readonly(
          "results_solve",
          [](S const& self)
          {
            t_ResSolve r;
            records(self.results_solve, self.nx(), r.t, r.x, r.q, false);
            return r;
          },
          "Trajectories of the last ``solve`` (``options.RESRECORD``), as "
          "NumPy arrays.")
      .def_property_readonly(
          "results_fsens",
          [](S const& self)
          {
            t_ResFsens r;
            records(self.results_fsens, self.nx(), r.t, r.xp, r.qp, false);
            return r;
          },
          "Trajectories of the last ``solve_fsens``, as NumPy arrays.")
      .def_property_readonly(
          "results_asens",
          [](S const& self)
          {
            t_ResAsens r;
            records(self.results_asens, self.nx(), r.t, r.l, r.qp, true);
            return r;
          },
          "Trajectories of the last ``solve_asens``, as NumPy arrays "
          "(ascending time).")
      .def_property_readonly(
          "stats_solve", [](S const& self) { return self.stats_solve; },
          "Statistics of the last ``solve``.")
      .def_property_readonly(
          "stats_fsens", [](S const& self) { return self.stats_fsens; },
          "Statistics of the last ``solve_fsens``.")
      .def_property_readonly(
          "stats_asens", [](S const& self) { return self.stats_asens; },
          "Statistics of the last ``solve_asens``.");
}
