// OCFE_PSA10b.cpp  ---  THE ACTUAL PSA REGIME: self-sharpening fronts, and the oscillations
//                      they generate.  DEMONSTRATION driver for the limiter/WENO case.
// ===========================================================================
// WHY THIS DRIVER EXISTS -- correcting the arc's framing
// ------------------------------------------------------
// PSA6..PSA9b measured the rung-9 model AS SHIPPED: D_ax = 0.1, k_ldf = 2.0, U = L = 1.
// Those numbers put the bed nowhere near a real PSA:
//
//     Pe = U*L/D_ax = 10          dispersive front width  ~ D/u_shock = 0.15  = 15% OF THE BED
//     LDF mass-transfer zone      ~ U*F*(dq*/dc)/k_ldf    = 0.25  = 25% OF THE BED
//     u_shock = U/(1+F*dq*/dc)    = 0.667                 (Langmuir, c 0 -> 0.5)
//
// i.e. the front is smeared over a quarter of the column and covered by ~4.5 collocation
// nodes.  The model CANNOT support a sharp front, so the arc found none, and the only
// oscillation left to find was the t=0 corner artefact -- real, but incidental.  Real PSA
// beds run Pe ~ 1e2..1e3 with fast kinetics, where the FAVOURABLE Langmuir isotherm makes the
// concentration front SELF-SHARPEN into a shock as it travels.  That is the regime in which
// flux limiters / WENO-type reconstruction are the standard remedy, and it has never been
// exercised here.
//
// THE SHARPNESS KNOB
// ------------------
// One parameter S drives the bed toward the low-dispersion, local-equilibrium limit:
//        D_ax = D0/S      lam = lam0/S      k_ldf = k0*S
// so dispersive and kinetic front widths shrink together and stay comparable (they would
// otherwise trade off and the front would stall at whichever is larger).  S = 1 is the model
// the whole arc used.  S = 100 gives Pe = 1000 and both widths ~0.2% of the bed -- about
// 1/15 of one collocation interval on the shipped z-mesh.
//
// WHAT IS DELIBERATELY REMOVED, so the measurement is unambiguous
// ---------------------------------------------------------------
// 1. THE STARTUP CORNER.  PSA5..PSA9's feed sits at cA against an empty bed, giving a
//    discontinuity at (z=0,t=0) -- which PSA9 showed is the dominant undershoot in that
//    configuration.  Here the feed is multiplied by a SHIFTED-NORMALISED tanh ramp,
//    r(0) = 0 and r(inf) = 1 EXACTLY, of width eps0 = 0.05 which the t-mesh resolves.  The
//    corner artefact is gone by construction.  (At high S it would NOT dissipate -- low D
//    means nothing smooths it -- so leaving it in would contaminate the whole field.)
// 2. THE INLET SWITCH IN t.  The composition switch at t*=2 has width eps and the t-mesh
//    always brackets it with 2 elements of width 4*eps (PSA7's law, W = 4*eps).  So the
//    inlet DATUM is resolved in t.
// => Whatever oscillation remains is generated by the SPATIAL FRONT INSIDE THE BED, which is
//    what a limiter would act on.  This is the point of the driver.
//
// AXES
// ----
//   A  S in {1,3,10,30,100} at the shipped z-mesh (5x6), sharp switch (eps=1e-3).
//      Onset and growth of the oscillation as the bed approaches the PSA limit.
//   B  z-refinement at high S (ne_z 5/10/20/40) -- what brute force actually costs.
//   C  SMOOTH inlet (eps=0.5) at high S.  THE DECISIVE CONFIG: if a sharp front forms and
//      rings anyway, the problem is NOT the inlet datum, it is the isotherm self-sharpening
//      the front internally -- and no amount of inlet smoothing or a-priori mesh grading can
//      pre-empt it, because the front's POSITION is part of the solution.
//
// METRICS -- chosen to map onto limiter theory, not invented here
// ---------------------------------------------------------------
//   TV(c1(.,t)) = \int_0^1 |dc1/dz| dz.  The exact solution is MONOTONE in z, so its total
//   variation is exactly |c1(0,t) - c1(1,t)|.  Any oscillation strictly increases TV.
//        TV_excess = ( TV - |c1(0)-c1(1)| ) / |c1(0)-c1(1)|
//   This is the quantity a TVD scheme bounds and a limiter enforces; TV_excess ~ 0 means
//   monotone, TV_excess = 0.5 means the profile wiggles by half its own range.  Reported
//   alongside the oscillation COUNT (sign changes of dc1/dz) and the undershoot.
//   Front POSITION and WIDTH are tracked at every snapshot: the front MOVES at u_shock, so a
//   mesh graded for it at one time is wrong at every other time -- the quantitative form of
//   "you cannot grade for a front whose location is part of the solution".
//
// Emits 2-D (z,t) field maps and z-profile snapshots for the flagged configs, so the
// oscillation can be seen rather than inferred.
// ===========================================================================

#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <vector>
#include <cmath>
#include <string>
#include <algorithm>

#ifndef OCFE_OCFESLV_HEADER
#define OCFE_OCFESLV_HEADER "ocfeslv.hpp"
#endif
#include OCFE_OCFESLV_HEADER

using namespace mc;

#ifndef PSA10_OUT_PREFIX
#define PSA10_OUT_PREFIX "OCFE_PSA10b"
#endif

// ---------- base model (rung-9 / PDE36c); D_ax, lam, k_ldf are now S-scaled ----------
static double const U_VEL = 1.0, F_ph = 0.5;
static double const D0 = 0.1, LAM0 = 0.1, K0 = 2.0;
static double const qs1 = 1.0, qs2 = 1.0, b01_nom = 3.0, b02_L = 1.0;
static double const beta1 = 2.0, beta2 = 1.0, T0_ref = 1.0;
static double const Cp_e = 1.0, G_cv = 1.0, dH1 = 1.0, dH2 = 0.5, hw = 0.5, Tw = 1.0;
static double const T_end = 5.0, t_step = 2.0;
static double const cA1 = 0.2, cB1 = 0.5, cA2 = 0.5, cB2 = 0.2;
static double const EPS0 = 0.05, START_KC = 4.0;      // resolved, IC-compatible startup ramp
static double const ZONE_KW = 4.0;

static inline double q1star_g( double a, double b ){ return qs1*b01_nom*a/( 1.0 + b01_nom*a + b02_L*b ); }
static inline double q2star_g( double a, double b ){ return qs2*b02_L*b/( 1.0 + b01_nom*a + b02_L*b ); }

struct Feed {
  double eps = 1e-3;
  double start( double t ) const {
    double const t0=START_KC*EPS0, Th=std::tanh(START_KC);
    return ( std::tanh((t-t0)/EPS0) + Th )/( 1.0 + Th ); }
  double sw( double t ) const { return 0.5*( 1.0 + std::tanh( (t-t_step)/eps ) ); }
  double c1( double t ) const { return start(t)*( cA1 + (cB1-cA1)*sw(t) ); }
  double c2( double t ) const { return start(t)*( cA2 + (cB2-cA2)*sw(t) ); }
};

// ---------- t-mesh: PSA7's law (G=2 geometric, budget 20) + PSA9's startup subdivision ----
static double series( double h0, double rho, size_t n )
{ if( n==0 ) return 0.;
  if( std::fabs(rho-1.0)<1e-12 ) return h0*double(n);
  return h0*rho*( std::pow(rho,double(n))-1.0 )/( rho-1.0 ); }
static double solve_ratio( double h0, double L, size_t n )
{ if( n==0 || !(L>0.) ) return 1.0;
  if( series(h0,1.0,n) >= L ) return 1.0;
  double a=1.0,b=2.0; while( series(h0,b,n)<L && b<1e8 ) b*=2.0;
  for( int i=0;i<200;++i ){ double const m=0.5*(a+b); if( series(h0,m,n)<L ) a=m; else b=m; }
  return 0.5*(a+b); }
static std::vector<double> geom_widths( double h0, double L, size_t n, double rho )
{ std::vector<double> w; if( n==0 ) return w;
  if( rho<=1.0+1e-12 ){ w.assign(n,L/double(n)); return w; }
  for( size_t k=0;k<n;++k ) w.push_back( h0*std::pow(rho,double(k+1)) );
  double s=0.; for(double x:w) s+=x; for(double& x:w) x*=L/s; return w; }

//! true iff every element has strictly positive width (checked BEFORE FFDom sees it, so a
//! bad mesh reports itself instead of surfacing as an opaque FFDom::Exceptions::TYPE)
static bool mesh_ok( std::vector<double> const& b, char const* what )
{
  if( b.size() < 2 ){ std::cerr << "  *** " << what << " mesh has < 1 element\n"; return false; }
  double hmin = 1e300;
  for( size_t i=0; i+1<b.size(); ++i ) hmin = std::min( hmin, b[i+1]-b[i] );
  if( !(hmin > 1e-12) ){
    std::cerr << "  *** DEGENERATE " << what << " MESH: min element width = " << hmin
              << " -- refusing to build FFDom\n"; return false; }
  return true;
}

static std::vector<double> t_mesh( double eps, size_t nsub )
{
  size_t const G=2, budget=20;
  // CLAMP.  The refinement zone must leave room for a real geometric fill on BOTH sides.
  // Unclamped, eps=0.5 gives W = ZONE_KW*eps = 2.0 = t_step exactly, so lo = 0, the left
  // fill has length ZERO, geom_widths() emits zero-width elements and FFDom throws
  // Exceptions::TYPE.  (This guard exists in PSA7's build_mesh and was lost when the law
  // was inlined here; axes A/B use eps=1e-3 where W=0.004, so only axis C tripped it.)
  double const Wmax = 0.4*std::min( t_step, T_end - t_step );
  double const W = std::min( ZONE_KW*eps, Wmax );
  double const lo=t_step-W, hi=t_step+W, h0=2.0*W/double(G);
  double const La=lo, Lc=T_end-hi;
  size_t const avail=budget-G;
  size_t bL=1,bR=avail-1; double best=1e300,rL=1.,rR=1.;
  for( size_t nl=1; nl<avail; ++nl ){
    size_t const nr=avail-nl;
    double const a=solve_ratio(h0,La,nl), b=solve_ratio(h0,Lc,nr);
    double const m=std::max(std::max(a,1.0/std::max(a,1e-30)),std::max(b,1.0/std::max(b,1e-30)));
    if( m<best ){ best=m; bL=nl; bR=nr; rL=a; rR=b; } }
  std::vector<double> const wl=geom_widths(h0,La,bL,rL), wr=geom_widths(h0,Lc,bR,rR);
  std::vector<double> b; b.push_back(0.);
  for( size_t i=wl.size(); i-->0; ) b.push_back( b.back()+wl[i] );
  for( size_t i=0;i<G;++i ) b.push_back( b.back()+h0 );
  for( size_t i=0;i<wr.size();++i ) b.push_back( b.back()+wr[i] );
  b.back()=T_end;
  if( nsub<=1 ) return b;
  double const W0=b[1];
  std::vector<double> w; w.push_back( W0*std::pow(0.5,double(nsub-1)) );
  for( size_t k=nsub-1; k>=1; --k ) w.push_back( W0*std::pow(0.5,double(k)) );
  std::vector<double> out; out.push_back(0.);
  for( double x : w ) out.push_back( out.back()+x );
  out.back()=W0;
  for( size_t i=2;i<b.size();++i ) out.push_back( b[i] );
  return out;
}

static std::vector<double> const SNAPS = { 0.5, 1.0, 1.5, 2.05, 2.2, 2.5, 3.0, 4.0 };

struct Cfg {
  double S=1.0, eps=1e-3;
  size_t ne_z=5, nn_z=6, nsub=4;
  bool   want_fields=false;
  std::string tag, name;
};

struct SR {
  Cfg cfg;
  bool converged=false; int iters=0; size_t nVar=0, nwin=0; double finalr=0.;
  double Pe=0., w_disp=0., w_ldf=0., h_z=0.;      // predicted front widths vs mesh
  double tv_max=0., osc_max=0.;                   // worst TV excess / oscillation count
  double tv_at=-1., mono_at=0.;                   // snapshot where tv_max occurred, and its mono
  double under_front=0., under_rel=0.;            // undershoot AFTER the startup ramp
  double q_min=0.;
  double zf_early=-1., zf_late=-1., wf_min=1e30;  // front position at 2 times, min width
};

// ---------------------------------------------------------------------------
static SR run_case( Cfg const& cfg, std::vector<double>& warm )
{
  SR R; R.cfg = cfg;
  double const D_ax = D0/cfg.S, lam = LAM0/cfg.S, k_ldf = K0*cfg.S;
  size_t const n_nd_t = 6;
  FFDom::TYPE const coltype = FFDom::LGL;
  Feed fd; fd.eps = cfg.eps;

  std::vector<double> const t_bnd = t_mesh( cfg.eps, cfg.nsub );
  std::vector<double> z_bnd; for( size_t i=0;i<=cfg.ne_z;++i ) z_bnd.push_back( double(i)/double(cfg.ne_z) );

  double const qf = q1star_g( cB1, cB2 ), ush = U_VEL/( 1.0 + F_ph*qf/std::max(cB1,1e-30) );
  R.Pe = U_VEL*1.0/D_ax;
  R.w_disp = D_ax/ush;
  R.w_ldf  = U_VEL*F_ph*(qf/std::max(cB1,1e-30))/k_ldf;
  R.h_z    = 1.0/double(cfg.ne_z*(cfg.nn_z-1));       // mean collocation interval in z

  std::cout << "\n---- " << cfg.name << "  S=" << std::fixed << std::setprecision(1) << cfg.S
            << "  D=" << std::scientific << std::setprecision(2) << D_ax
            << " k=" << std::fixed << std::setprecision(1) << k_ldf
            << "  Pe=" << std::setprecision(0) << R.Pe
            << "  eps=" << std::scientific << std::setprecision(1) << cfg.eps
            << "  z " << cfg.ne_z << "x" << cfg.nn_z
            << "   front widths: disp=" << std::setprecision(2) << R.w_disp
            << " ldf=" << R.w_ldf << " vs dz=" << R.h_z
            << "  (" << std::fixed << std::setprecision(2)
            << std::max(R.w_disp,R.w_ldf)/R.h_z << " nodes across)   " << cfg.tag << " ----\n";

  FFGraph DAG;
  FFVar t=DAG.add_var("t"), z=DAG.add_var("z");
  FFVar c1=DAG.add_var("c1(t,z)"), c2=DAG.add_var("c2(t,z)");
  FFVar q1=DAG.add_var("q1(t,z)"), q2=DAG.add_var("q2(t,z)"), T=DAG.add_var("T(t,z)");

  FFPartial  OpP;
  FFIntegral OpI;

  double const s0 = START_KC*EPS0, Sh = std::tanh( START_KC );
  FFVar rstart = ( tanh( ( t - s0 )/EPS0 ) + Sh )/( 1.0 + Sh );
  FFVar sw     = 0.5*( 1.0 + tanh( ( t - t_step )/cfg.eps ) );
  FFVar c1feed = rstart*( cA1 + ( cB1 - cA1 )*sw );
  FFVar c2feed = rstart*( cA2 + ( cB2 - cA2 )*sw );

  FFVar b1 = b01_nom*exp( beta1*( 1.0/T - 1.0/T0_ref ) );
  FFVar b2 = b02_L  *exp( beta2*( 1.0/T - 1.0/T0_ref ) );
  FFVar den = 1.0 + b1*c1 + b2*c2;
  FFVar q1star = qs1*b1*c1/den, q2star = qs2*b2*c2/den;

  FFVar CONT1 = OpP( c1, t ) + U_VEL*OpP( c1, z ) - D_ax*OpP( OpP( c1, z ), z ) + F_ph*OpP( q1, t );
  FFVar CONT2 = OpP( c2, t ) + U_VEL*OpP( c2, z ) - D_ax*OpP( OpP( c2, z ), z ) + F_ph*OpP( q2, t );
  FFVar LDF1  = OpP( q1, t ) - k_ldf*( q1star - q1 );
  FFVar LDF2  = OpP( q2, t ) - k_ldf*( q2star - q2 );
  FFVar ENE_T = Cp_e*OpP( T, t ) + G_cv*OpP( T, z ) - lam*OpP( OpP( T, z ), z )
              - F_ph*( dH1*OpP( q1, t ) + dH2*OpP( q2, t ) ) + hw*( T - Tw );
  FFVar IC_c1 = c1, IC_c2 = c2, IC_q1 = q1, IC_q2 = q2, IC_T = T - T0_ref;
  FFVar BC_L1 = U_VEL*c1 - D_ax*OpP( c1, z ) - U_VEL*c1feed;
  FFVar BC_L2 = U_VEL*c2 - D_ax*OpP( c2, z ) - U_VEL*c2feed;
  FFVar BC_LT = G_cv*T - lam*OpP( T, z ) - G_cv*T0_ref;
  FFVar BC_U1 = OpP( c1, z ), BC_U2 = OpP( c2, z ), BC_UT = OpP( T, z );
  FFVar Inv1 = OpI( c1 + F_ph*q1, z ), Eff1 = OpI( U_VEL*c1, t );

  OCFESLV oc( &DAG );
  oc.add_domain( t, FFDom( t_bnd, coltype, n_nd_t ) );
  oc.add_domain( z, FFDom( z_bnd, coltype, cfg.nn_z ) );
  oc.add_state ( c1, {t,z} ); oc.add_state( c2, {t,z} );
  oc.add_state ( q1, {t,z} ); oc.add_state( q2, {t,z} ); oc.add_state( T, {t,z} );

  // update_ref LIFETIME: FFVars by reference (they outlive init() here), all else BY VALUE
  auto c1g = [&t,&z,fd]( OCFESLV::t_Coord const& cr ){ return fd.c1(cr.at(t))*(1.0-0.5*cr.at(z)); };
  auto c2g = [&t,&z,fd]( OCFESLV::t_Coord const& cr ){ return fd.c2(cr.at(t))*(1.0-0.5*cr.at(z)); };
  oc.update_ref( c1, c1g );
  oc.update_ref( c2, c2g );
  oc.update_ref( q1, [c1g,c2g]( OCFESLV::t_Coord const& cr ){ return q1star_g(c1g(cr),c2g(cr)); } );
  oc.update_ref( q2, [c1g,c2g]( OCFESLV::t_Coord const& cr ){ return q2star_g(c1g(cr),c2g(cr)); } );
  oc.update_ref( T,  [c1g,c2g]( OCFESLV::t_Coord const& cr ){
    return T0_ref + F_ph*( dH1*q1star_g(c1g(cr),c2g(cr)) + dH2*q2star_g(c1g(cr),c2g(cr)) )/Cp_e; } );
  oc.set_evolution_domain( t );

  int const T_NO_LB = FFDom::ALL - FFDom::LB;
  int const Z_INT   = FFDom::ALL - FFDom::LB - FFDom::UB;
  oc.add_equation( CONT1, {t,z}, {T_NO_LB,   Z_INT},      OCFESLV::EqnOptions( OCFESLV::EqnRole::INTERIOR, 0 ) );
  oc.add_equation( CONT2, {t,z}, {T_NO_LB,   Z_INT},      OCFESLV::EqnOptions( OCFESLV::EqnRole::INTERIOR, 0 ) );
  oc.add_equation( LDF1,  {t,z}, {T_NO_LB,   FFDom::ALL}, OCFESLV::EqnOptions( OCFESLV::EqnRole::INTERIOR, 0 ) );
  oc.add_equation( LDF2,  {t,z}, {T_NO_LB,   FFDom::ALL}, OCFESLV::EqnOptions( OCFESLV::EqnRole::INTERIOR, 0 ) );
  oc.add_equation( ENE_T, {t,z}, {T_NO_LB,   Z_INT},      OCFESLV::EqnOptions( OCFESLV::EqnRole::INTERIOR, 0 ) );
  oc.add_equation( IC_c1, {t,z}, {FFDom::LB, FFDom::ALL}, OCFESLV::EqnOptions( OCFESLV::EqnRole::INITIAL,  0 ) );
  oc.add_equation( IC_c2, {t,z}, {FFDom::LB, FFDom::ALL}, OCFESLV::EqnOptions( OCFESLV::EqnRole::INITIAL,  0 ) );
  oc.add_equation( IC_q1, {t,z}, {FFDom::LB, FFDom::ALL}, OCFESLV::EqnOptions( OCFESLV::EqnRole::INITIAL,  0 ) );
  oc.add_equation( IC_q2, {t,z}, {FFDom::LB, FFDom::ALL}, OCFESLV::EqnOptions( OCFESLV::EqnRole::INITIAL,  0 ) );
  oc.add_equation( IC_T,  {t,z}, {FFDom::LB, FFDom::ALL}, OCFESLV::EqnOptions( OCFESLV::EqnRole::INITIAL,  0 ) );
  oc.add_equation( BC_L1, {t,z}, {T_NO_LB,   FFDom::LB},  OCFESLV::EqnOptions( OCFESLV::EqnRole::BOUNDARY, 0 ) );
  oc.add_equation( BC_L2, {t,z}, {T_NO_LB,   FFDom::LB},  OCFESLV::EqnOptions( OCFESLV::EqnRole::BOUNDARY, 0 ) );
  oc.add_equation( BC_LT, {t,z}, {T_NO_LB,   FFDom::LB},  OCFESLV::EqnOptions( OCFESLV::EqnRole::BOUNDARY, 0 ) );
  oc.add_equation( BC_U1, {t,z}, {T_NO_LB,   FFDom::UB},  OCFESLV::EqnOptions( OCFESLV::EqnRole::BOUNDARY, 0 ) );
  oc.add_equation( BC_U2, {t,z}, {T_NO_LB,   FFDom::UB},  OCFESLV::EqnOptions( OCFESLV::EqnRole::BOUNDARY, 0 ) );
  oc.add_equation( BC_UT, {t,z}, {T_NO_LB,   FFDom::UB},  OCFESLV::EqnOptions( OCFESLV::EqnRole::BOUNDARY, 0 ) );
  oc.add_output( Inv1, {t}, {T_end} );
  oc.add_output( Eff1, {z}, {1.0}   );

  oc.options.REDUCE.ORDER     = OCFESLV::Options::RED_FULL;
  oc.options.CLASSIFY.MODE         = OCFESLV::Options::CLASS_AUTO;
  oc.options.INTERFACE.TYPE   = OCFESLV::Options::IC_AUTO;
  oc.options.INTERFACE.IMPOSITION  = OCFESLV::Options::IC_STRONG;
  oc.options.INTERFACE.SAT_SIGMA0       = 10.0;
  oc.options.DISPLAY_LEVEL    = 0;
#if defined(CRONOS__WITH_SPQR)
  oc.options.SOLVE.FACTORIZATION = OCFESLV::Options::SOLVE_SPQR;
#else
  oc.options.SOLVE.FACTORIZATION = OCFESLV::Options::SOLVE_SUPERLU;
#endif
  oc.options.SOLVE.WARMSTART        = OCFESLV::Options::BROADCAST_IC;
  oc.options.OUTPUT.MARCH_STORE = true;

  if( !mesh_ok(t_bnd,"t") || !mesh_ok(z_bnd,"z") ) return R;
  if( !oc.setup() ){ std::cerr << "  setup() FAILED\n"; return R; }
  std::vector<double> varInit, inp;
  if( !oc.init( varInit, inp, nullptr ) ){ std::cerr << "  init() FAILED\n"; return R; }
  R.nVar=oc.n_colloc_sta(); R.nwin=oc.n_march_steps();

  // S-continuation: warm-start from the previous (milder) S on the SAME mesh only
  std::vector<double> xv = ( warm.size()==varInit.size() ? warm : varInit );
  OCFESLV::SolveReport const rep = oc.solve( xv.data(), inp.data(), nullptr );
  R.converged=rep.converged; R.iters=rep.iterations; R.finalr=rep.final_residual;
  std::cout << "  nVar=" << R.nVar << " windows=" << R.nwin
            << " converged=" << (rep.converged?"yes":"no") << " iters=" << rep.iterations
            << " final|r|=" << std::scientific << std::setprecision(3) << rep.final_residual << "\n";
  if( !rep.converged ){
    std::cout << "  *** NEWTON FAILED -- this IS a result: the shipped scheme cannot solve"
                 " the bed at Pe=" << std::fixed << std::setprecision(0) << R.Pe << " ***\n";
    return R; }
  warm = xv;

  auto Vv = [&]( FFVar const& v, double zz, double tt ){
    OCFESLV::t_Coord pt; pt[z]=zz; pt[t]=tt;
    return oc.eval_colloc<double>( v, pt, xv.data(), inp.data(), nullptr ); };

  // ---- TV / oscillation / front metrics at each snapshot ----
  double const CSCALE = std::max( cA1, cB1 );        // fixed reference scale for TV
  size_t const NZ = 1500;
  std::vector<double> prof( NZ+1 );
  std::ofstream pf( std::string(PSA10_OUT_PREFIX)+"_profile_"+cfg.name+".out" );
  pf << "# z-profiles, one block per snapshot   # z c1 c2 q1 q2 T\n";
  for( double tt : SNAPS ){
    for( size_t k=0;k<=NZ;++k ) prof[k] = Vv( c1, double(k)/double(NZ), tt );
    double tv=0.; size_t osc=0; int sgn=0;
    double mn=1e30;
    for( size_t k=0;k<NZ;++k ){
      double const d = prof[k+1]-prof[k];
      tv += std::fabs(d);
      if( std::fabs(d) > 1e-9 ){ int const s = (d>0? 1 : -1); if( sgn && s!=sgn ) ++osc; sgn=s; } }
    for( size_t k=0;k<=NZ;++k ) mn = std::min( mn, prof[k] );
    // TV excess normalised by a FIXED concentration scale, NOT by the instantaneous
    // monotone variation.  After breakthrough c1(0) ~ c1(1) so mono -> 0, and the
    // original (tv-mono)/mono blew up on a vanishing denominator -- which is why PSA10's
    // S=100 row read LOWER than S=30.  mono is carried through so the degeneracy stays visible.
    double const mono = std::fabs( prof[0]-prof[NZ] );
    double const tvx  = ( tv - mono )/CSCALE;
    if( tvx > R.tv_max ){ R.tv_max=tvx; R.tv_at=tt; R.mono_at=mono; }
    R.osc_max = std::max( R.osc_max, double(osc) );
    if( tt > 4.0*EPS0 ){                                  // AFTER the resolved startup ramp
      R.under_front = std::min( R.under_front, std::min(0.0,mn) );
      R.under_rel   = R.under_front/std::max(prof[0],1e-30); }
    // front position (mid-crossing) and 10-90% width
    double const lo=prof[NZ], hi=prof[0], rng=hi-lo;
    if( rng > 1e-6 ){
      auto cross = [&]( double frac )->double {
        double const target = lo + frac*rng;
        for( size_t k=0;k<NZ;++k )
          if( (prof[k]-target)*(prof[k+1]-target) <= 0. ){
            double const w = (target-prof[k])/((prof[k+1]-prof[k])+1e-300);
            return (double(k)+w)/double(NZ); }
        return -1.; };
      double const z50=cross(0.5), z90=cross(0.9), z10=cross(0.1);
      if( std::fabs(tt-1.0)<1e-9 ) R.zf_early=z50;
      if( std::fabs(tt-3.0)<1e-9 ) R.zf_late =z50;
      if( z10>0. && z90>0. && z10>z90 ) R.wf_min = std::min( R.wf_min, z10-z90 ); }
    pf << "\n\n# t=" << tt << "  TVexcess=" << tvx << " osc=" << osc << "\n";
    for( size_t k=0;k<=NZ;k+=5 ){ double const zz=double(k)/double(NZ);
      pf << std::setprecision(8) << zz << " " << prof[k] << " " << Vv(c2,zz,tt) << " "
         << Vv(q1,zz,tt) << " " << Vv(q2,zz,tt) << " " << Vv(T,zz,tt) << "\n"; } }

  { double qm=1e30;
    for( size_t k=0;k<=60;++k ) for( double tt : SNAPS )
      qm = std::min( qm, std::min( Vv(q1,double(k)/60.0,tt), Vv(q2,double(k)/60.0,tt) ) );
    R.q_min = qm; }
  if( R.wf_min>1e29 ) R.wf_min = -1.;

  std::cout << std::scientific << std::setprecision(3)
            << "  TV excess max=" << R.tv_max << " at t=" << std::fixed << std::setprecision(2) << R.tv_at
            << " (mono there=" << std::scientific << std::setprecision(2) << R.mono_at << ")"
            << "   oscillations=" << std::setprecision(0) << R.osc_max
            << "   undershoot(front)=" << std::scientific << std::setprecision(3) << R.under_front
            << " (" << std::fixed << std::setprecision(2) << 100.0*R.under_rel << "% of feed)"
            << "   min q=" << std::scientific << std::setprecision(2) << R.q_min << "\n"
            << "  front: z(t=1)=" << std::fixed << std::setprecision(4) << R.zf_early
            << " z(t=3)=" << R.zf_late << "  moved " << R.zf_late-R.zf_early
            << "   min 10-90% width=" << std::scientific << std::setprecision(2) << R.wf_min
            << "  (dz=" << R.h_z << ")\n";

  if( cfg.want_fields ){
    std::ofstream f( std::string(PSA10_OUT_PREFIX)+"_field_"+cfg.name+".out" );
    f << "# z t c1 c2 q1 q2 T   (blank line between z-blocks: splot ... w pm3d)\n";
    for( size_t iz=0; iz<=120; ++iz ){ double const zz=double(iz)/120.0;
      for( size_t it=0; it<=120; ++it ){ double const tt=T_end*double(it)/120.0;
        f << std::setprecision(8) << zz << " " << tt << " "
          << Vv(c1,zz,tt) << " " << Vv(c2,zz,tt) << " "
          << Vv(q1,zz,tt) << " " << Vv(q2,zz,tt) << " " << Vv(T,zz,tt) << "\n"; }
      f << "\n"; }
    std::cout << "  wrote field map for '" << cfg.name << "'\n"; }
  return R;
}

// ---------------------------------------------------------------------------
int main()
{
  // Unbuffered: "\n" does not flush std::cout, and terminate()->abort() DISCARDS the
  // buffer -- which is how PSA10 lost its last result line when a later config threw.
  std::cout.setf( std::ios::unitbuf );
  std::cout << "================================================================\n"
            << "  PSA10b -- the ACTUAL PSA regime: self-sharpening fronts\n"
            << "  S scales D_ax=D0/S, lam=lam0/S, k_ldf=k0*S toward local equilibrium\n"
            << "  S=1 is the model the whole arc used (Pe=10, front = 15%% of the bed)\n"
            << "================================================================\n";

  std::vector<SR> rows;

  // AXIS A -- approach the PSA limit at the shipped z-mesh, S-continuation
  { std::vector<double> warm;
    for( double S : { 1.0, 3.0, 10.0, 30.0, 100.0 } ){
      Cfg c; c.S=S; c.tag="A: approach the PSA limit";
      std::ostringstream nm; nm << "S" << (int)S; c.name=nm.str();
      c.want_fields = ( S==1.0 || S==30.0 || S==100.0 );
      rows.push_back( run_case( c, warm ) ); } }

  // AXIS B -- what brute-force z-refinement costs at high S (each its own continuation)
  for( size_t nz : { size_t(10), size_t(20), size_t(40), size_t(80) } ){
    std::vector<double> warm; SR last;
    for( double S : { 1.0, 3.0, 10.0, 30.0, 100.0 } ){
      Cfg c; c.S=S; c.ne_z=nz; c.tag="B: z-refinement";
      std::ostringstream nm; nm << "S" << (int)S << "z" << nz; c.name=nm.str();
      last = run_case( c, warm );
      if( S==30.0 || S==100.0 ) rows.push_back( last ); } }

  // AXIS C -- SMOOTH inlet at high S.  If the front sharpens and rings ANYWAY, the inlet
  // datum is not the cause and no a-priori mesh grading can pre-empt it.
  { std::vector<double> warm;
    for( double S : { 1.0, 3.0, 10.0, 30.0, 100.0 } ){
      Cfg c; c.S=S; c.eps=0.5; c.tag="C: SMOOTH inlet (eps=0.5)";
      std::ostringstream nm; nm << "smoothS" << (int)S; c.name=nm.str();
      c.want_fields = ( S==30.0 || S==100.0 );
      SR r = run_case( c, warm );
      if( S==30.0 || S==100.0 ) rows.push_back( r ); } }

  std::cout << "\n============================== PSA10 TABLE ==============================\n"
            << std::left << std::setw(12) << "case" << std::setw(8) << "S"
            << std::setw(10) << "eps" << std::setw(6) << "ne_z"
            << std::right << std::setw(9) << "Pe" << std::setw(10) << "w_front"
            << std::setw(10) << "dz" << std::setw(8) << "n/front" << std::setw(5) << "it"
            << std::setw(11) << "TVexcess" << std::setw(6) << "osc"
            << std::setw(11) << "under" << std::setw(9) << "%feed"
            << std::setw(11) << "min q" << "\n";
  for( SR const& R : rows ){
    double const wf = std::max(R.w_disp,R.w_ldf);
    std::cout << std::left << std::setw(12) << R.cfg.name
              << std::fixed << std::setprecision(1) << std::setw(8) << R.cfg.S
              << std::scientific << std::setprecision(1) << std::setw(10) << R.cfg.eps
              << std::left << std::setw(6) << R.cfg.ne_z
              << std::right << std::fixed << std::setprecision(0) << std::setw(9) << R.Pe
              << std::scientific << std::setprecision(2) << std::setw(10) << wf
              << std::setw(10) << R.h_z
              << std::fixed << std::setprecision(2) << std::setw(8) << wf/R.h_z
              << std::setw(5) << R.iters;
    if( !R.converged ){ std::cout << "   *** NEWTON FAILED ***\n"; continue; }
    std::cout << std::scientific << std::setprecision(2) << std::setw(11) << R.tv_max
              << std::fixed << std::setprecision(0) << std::setw(6) << R.osc_max
              << std::scientific << std::setprecision(2) << std::setw(11) << R.under_front
              << std::fixed << std::setprecision(2) << std::setw(9) << 100.0*R.under_rel
              << std::scientific << std::setprecision(2) << std::setw(11) << R.q_min << "\n"; }

  std::cout << "\n  READING THE TABLE\n"
               "  n/front is the number of collocation intervals spanning the physical front.\n"
               "  Above ~2 the scheme has a chance; below ~1 it is representing a near-\n"
               "  discontinuity with a degree-5 polynomial and MUST ring.\n"
               "  TVexcess is the canonical limiter metric: the exact profile is MONOTONE in z,\n"
               "  so its total variation is exactly |c(0)-c(1)| and ANY oscillation raises it.\n"
               "  TVexcess ~ 0 monotone; ~0.1 a visible wiggle; >0.5 the profile oscillates by\n"
               "  half its own range.  This is precisely the quantity a TVD/TVB limiter bounds.\n"
               "  AXIS C IS THE DECISIVE ONE: a SMOOTH inlet (eps=0.5) at high S.  If TVexcess\n"
               "  and the undershoot are comparable to the sharp-inlet rows, the oscillation is\n"
               "  generated by the ISOTHERM self-sharpening the front INSIDE the bed -- not by\n"
               "  the inlet datum.  Then inlet smoothing cannot help, and neither can a mesh\n"
               "  graded a priori, because the front MOVES (see z(t=1) vs z(t=3)).  That is the\n"
               "  case for a limiter / WENO-type reconstruction, and it is the case 0r never\n"
               "  actually exhibited.\n";

  { std::ofstream f( std::string(PSA10_OUT_PREFIX)+"_summary.out" );
    f << "# name S eps ne_z nVar Pe w_disp w_ldf dz iters TVexcess tv_at osc under_front "
         "under_rel q_min zf1 zf3 wf_min conv\n";
    for( SR const& R : rows )
      f << R.cfg.name << " " << std::setprecision(8) << R.cfg.S << " " << R.cfg.eps << " "
        << R.cfg.ne_z << " " << R.nVar << " " << R.Pe << " " << R.w_disp << " " << R.w_ldf << " "
        << R.h_z << " " << R.iters << " " << R.tv_max << " " << R.tv_at << " " << R.osc_max << " "
        << R.under_front << " " << R.under_rel << " " << R.q_min << " "
        << R.zf_early << " " << R.zf_late << " " << R.wf_min << " " << (R.converged?1:0) << "\n"; }

  { std::ofstream gp( std::string(PSA10_OUT_PREFIX)+".gp" );
    gp << "set datafile commentschars '#'\n"
          "set terminal pngcairo size 1050,720 enhanced font 'Helvetica,12'\n"
          "set grid\n\n"
          "set output '" << PSA10_OUT_PREFIX << "_profiles_S100.png'\n"
          "set title 'c_1 z-profiles, S=100 (Pe=1000): the front and its ringing'\n"
          "set xlabel 'z'; set ylabel 'c_1'; set key outside\n"
          "plot for [i=0:7] '" << PSA10_OUT_PREFIX << "_profile_S100.out' index i u 1:2 "
          "w l lw 2 t 'snap '.i, 0 w l lt 0 lw 2 notitle\n\n"
          "set output '" << PSA10_OUT_PREFIX << "_profiles_smoothS30.png'\n"
          "set title 'c_1 z-profiles, SMOOTH inlet, S=30: the shock forms internally'\n"
          "plot for [i=0:7] '" << PSA10_OUT_PREFIX << "_profile_smoothS30.out' index i u 1:2 "
          "w l lw 2 t 'snap '.i, 0 w l lt 0 lw 2 notitle\n\n"
          "set output '" << PSA10_OUT_PREFIX << "_tv.png'\n"
          "set title 'TV excess vs collocation intervals across the front'\n"
          "set xlabel 'front width / dz'; set ylabel 'TV excess'; set logscale xy\n"
          "plot '" << PSA10_OUT_PREFIX << "_summary.out' u ($7>$8?$7:$8)/$9:11 w p pt 7 ps 1.5 notitle\n"
          "unset logscale\n\n"
          "set pm3d map interpolate 2,2\n"
          "set palette defined (0 '#08306b', 0.5 '#6baed6', 1 '#a50026')\n"
          "set xlabel 'z'; set ylabel 't'\n";
    char const* cs[3] = { "S1", "S30", "S100" };
    for( int i=0;i<3;++i )
      gp << "set output '" << PSA10_OUT_PREFIX << "_map_" << cs[i] << "_c1.png'\n"
            "set title 'c_1(z,t)  --  " << cs[i] << "'\n"
            "splot '" << PSA10_OUT_PREFIX << "_field_" << cs[i] << ".out' u 1:2:3 notitle w pm3d\n\n"; }

  size_t nconv=0; for( SR const& R : rows ) nconv += (R.converged?1:0);
  std::cout << "\n  wrote " << PSA10_OUT_PREFIX << "_summary.out, _profile_*.out, _field_*.out and .gp\n"
            << "  converged " << nconv << "/" << rows.size()
            << "  (non-convergence at high S is itself a reportable result)\n";
  return 0;
}
